// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2CreditLoopedPositionsChain string

const (
	V2CreditLoopedPositionsChainArbitrum V2CreditLoopedPositionsChain = "arbitrum"
	V2CreditLoopedPositionsChainBase     V2CreditLoopedPositionsChain = "base"
	V2CreditLoopedPositionsChainBsc      V2CreditLoopedPositionsChain = "bsc"
	V2CreditLoopedPositionsChainEthereum V2CreditLoopedPositionsChain = "ethereum"
	V2CreditLoopedPositionsChainTempo    V2CreditLoopedPositionsChain = "tempo"
)

func (e V2CreditLoopedPositionsChain) ToPointer() *V2CreditLoopedPositionsChain {
	return &e
}
func (e *V2CreditLoopedPositionsChain) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "arbitrum":
		fallthrough
	case "base":
		fallthrough
	case "bsc":
		fallthrough
	case "ethereum":
		fallthrough
	case "tempo":
		*e = V2CreditLoopedPositionsChain(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V2CreditLoopedPositionsChain: %v", v)
	}
}

type V2CreditLoopedPositionsRequest struct {
	Chain V2CreditLoopedPositionsChain `queryParam:"style=form,explode=true,name=chain"`
	// The address of the owner of the credit account to get looped positions for.
	Owner string `queryParam:"style=form,explode=true,name=owner"`
}

func (v *V2CreditLoopedPositionsRequest) GetChain() V2CreditLoopedPositionsChain {
	if v == nil {
		return V2CreditLoopedPositionsChain("")
	}
	return v.Chain
}

func (v *V2CreditLoopedPositionsRequest) GetOwner() string {
	if v == nil {
		return ""
	}
	return v.Owner
}

// #region class-body-v2creditloopedpositionsrequest
// #endregion class-body-v2creditloopedpositionsrequest

type V2CreditLoopedPositionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	CreditLoopedPositionsResponse *components.CreditLoopedPositionsResponse
}

func (v V2CreditLoopedPositionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2CreditLoopedPositionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2CreditLoopedPositionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2CreditLoopedPositionsResponse) GetCreditLoopedPositionsResponse() *components.CreditLoopedPositionsResponse {
	if v == nil {
		return nil
	}
	return v.CreditLoopedPositionsResponse
}

// #region class-body-v2creditloopedpositionsresponse
// #endregion class-body-v2creditloopedpositionsresponse
