// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2CreditBundleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	CreditBundleResponse *components.CreditBundleResponse
}

func (v V2CreditBundleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2CreditBundleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2CreditBundleResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2CreditBundleResponse) GetCreditBundleResponse() *components.CreditBundleResponse {
	if v == nil {
		return nil
	}
	return v.CreditBundleResponse
}

// #region class-body-v2creditbundleresponse
// #endregion class-body-v2creditbundleresponse
