// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2CreditMorphoMarketsChain string

const (
	V2CreditMorphoMarketsChainArbitrum V2CreditMorphoMarketsChain = "arbitrum"
	V2CreditMorphoMarketsChainBase     V2CreditMorphoMarketsChain = "base"
	V2CreditMorphoMarketsChainBsc      V2CreditMorphoMarketsChain = "bsc"
	V2CreditMorphoMarketsChainEthereum V2CreditMorphoMarketsChain = "ethereum"
	V2CreditMorphoMarketsChainHyperevm V2CreditMorphoMarketsChain = "hyperevm"
	V2CreditMorphoMarketsChainTempo    V2CreditMorphoMarketsChain = "tempo"
)

func (e V2CreditMorphoMarketsChain) ToPointer() *V2CreditMorphoMarketsChain {
	return &e
}
func (e *V2CreditMorphoMarketsChain) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "arbitrum":
		fallthrough
	case "base":
		fallthrough
	case "bsc":
		fallthrough
	case "ethereum":
		fallthrough
	case "hyperevm":
		fallthrough
	case "tempo":
		*e = V2CreditMorphoMarketsChain(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V2CreditMorphoMarketsChain: %v", v)
	}
}

// MorphoMarketOrderBy - Columns the Morpho markets list can be ordered by. All are stored by the
// indexer, so ordering + paging happen on the DB set before the (expensive)
// per-market on-chain enrichment — only the requested page is read on-chain.
type MorphoMarketOrderBy string

const (
	MorphoMarketOrderByTvlUsd       MorphoMarketOrderBy = "tvl_usd"
	MorphoMarketOrderByLiquidityUsd MorphoMarketOrderBy = "liquidity_usd"
	MorphoMarketOrderByLltv         MorphoMarketOrderBy = "lltv"
)

func (e MorphoMarketOrderBy) ToPointer() *MorphoMarketOrderBy {
	return &e
}
func (e *MorphoMarketOrderBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tvl_usd":
		fallthrough
	case "liquidity_usd":
		fallthrough
	case "lltv":
		*e = MorphoMarketOrderBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MorphoMarketOrderBy: %v", v)
	}
}

// V2CreditMorphoMarketsDirection - Order direction (asc/desc).
type V2CreditMorphoMarketsDirection string

const (
	V2CreditMorphoMarketsDirectionAsc  V2CreditMorphoMarketsDirection = "asc"
	V2CreditMorphoMarketsDirectionDesc V2CreditMorphoMarketsDirection = "desc"
)

func (e V2CreditMorphoMarketsDirection) ToPointer() *V2CreditMorphoMarketsDirection {
	return &e
}
func (e *V2CreditMorphoMarketsDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = V2CreditMorphoMarketsDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V2CreditMorphoMarketsDirection: %v", v)
	}
}

type V2CreditMorphoMarketsRequest struct {
	// The offset of the first item to return.
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// The number of items to return.
	Limit *int64                     `queryParam:"style=form,explode=true,name=limit"`
	Chain V2CreditMorphoMarketsChain `queryParam:"style=form,explode=true,name=chain"`
	// Field to order the markets by before paginating.
	OrderBy *MorphoMarketOrderBy `queryParam:"style=form,explode=true,name=order_by"`
	// Order direction (asc/desc).
	Direction *V2CreditMorphoMarketsDirection `queryParam:"style=form,explode=true,name=direction"`
}

func (v *V2CreditMorphoMarketsRequest) GetOffset() *int64 {
	if v == nil {
		return nil
	}
	return v.Offset
}

func (v *V2CreditMorphoMarketsRequest) GetLimit() *int64 {
	if v == nil {
		return nil
	}
	return v.Limit
}

func (v *V2CreditMorphoMarketsRequest) GetChain() V2CreditMorphoMarketsChain {
	if v == nil {
		return V2CreditMorphoMarketsChain("")
	}
	return v.Chain
}

func (v *V2CreditMorphoMarketsRequest) GetOrderBy() *MorphoMarketOrderBy {
	if v == nil {
		return nil
	}
	return v.OrderBy
}

func (v *V2CreditMorphoMarketsRequest) GetDirection() *V2CreditMorphoMarketsDirection {
	if v == nil {
		return nil
	}
	return v.Direction
}

// #region class-body-v2creditmorphomarketsrequest
// #endregion class-body-v2creditmorphomarketsrequest

type V2CreditMorphoMarketsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	MorphoMarketsResponse *components.MorphoMarketsResponse
}

func (v V2CreditMorphoMarketsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2CreditMorphoMarketsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2CreditMorphoMarketsResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2CreditMorphoMarketsResponse) GetMorphoMarketsResponse() *components.MorphoMarketsResponse {
	if v == nil {
		return nil
	}
	return v.MorphoMarketsResponse
}

// #region class-body-v2creditmorphomarketsresponse
// #endregion class-body-v2creditmorphomarketsresponse
