// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2GasSponsorshipApproveTransferResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ApproveTransferResponse *components.ApproveTransferResponse
}

func (v V2GasSponsorshipApproveTransferResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2GasSponsorshipApproveTransferResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2GasSponsorshipApproveTransferResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2GasSponsorshipApproveTransferResponse) GetApproveTransferResponse() *components.ApproveTransferResponse {
	if v == nil {
		return nil
	}
	return v.ApproveTransferResponse
}

// #region class-body-v2gassponsorshipapprovetransferresponse
// #endregion class-body-v2gassponsorshipapprovetransferresponse
