// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2GlobalMarketsPerpsExecuteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	GlobalMarketsPerpsExecuteResponse *components.GlobalMarketsPerpsExecuteResponse
}

func (v V2GlobalMarketsPerpsExecuteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2GlobalMarketsPerpsExecuteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2GlobalMarketsPerpsExecuteResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2GlobalMarketsPerpsExecuteResponse) GetGlobalMarketsPerpsExecuteResponse() *components.GlobalMarketsPerpsExecuteResponse {
	if v == nil {
		return nil
	}
	return v.GlobalMarketsPerpsExecuteResponse
}

// #region class-body-v2globalmarketsperpsexecuteresponse
// #endregion class-body-v2globalmarketsperpsexecuteresponse
