// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2GlobalMarketsPerpsWithdrawResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	GlobalMarketsPerpsSignableActionResponse *components.GlobalMarketsPerpsSignableActionResponse
}

func (v V2GlobalMarketsPerpsWithdrawResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2GlobalMarketsPerpsWithdrawResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2GlobalMarketsPerpsWithdrawResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2GlobalMarketsPerpsWithdrawResponse) GetGlobalMarketsPerpsSignableActionResponse() *components.GlobalMarketsPerpsSignableActionResponse {
	if v == nil {
		return nil
	}
	return v.GlobalMarketsPerpsSignableActionResponse
}

// #region class-body-v2globalmarketsperpswithdrawresponse
// #endregion class-body-v2globalmarketsperpswithdrawresponse
