// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// Generated under the AGPL-3.0-only license.
// SPDX-License-Identifier: AGPL-3.0-only

package operations

import (
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2PerpetualTradingCancelOrderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PerpetualTradingSignableActionResponse *components.PerpetualTradingSignableActionResponse
}

func (v V2PerpetualTradingCancelOrderResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2PerpetualTradingCancelOrderResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2PerpetualTradingCancelOrderResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2PerpetualTradingCancelOrderResponse) GetPerpetualTradingSignableActionResponse() *components.PerpetualTradingSignableActionResponse {
	if v == nil {
		return nil
	}
	return v.PerpetualTradingSignableActionResponse
}

// #region class-body-v2perpetualtradingcancelorderresponse
// #endregion class-body-v2perpetualtradingcancelorderresponse
