// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2PerpetualTradingEnableUnifiedAccountResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PerpetualTradingEnableUnifiedAccountResponse *components.PerpetualTradingEnableUnifiedAccountResponse
}

func (v V2PerpetualTradingEnableUnifiedAccountResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2PerpetualTradingEnableUnifiedAccountResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2PerpetualTradingEnableUnifiedAccountResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2PerpetualTradingEnableUnifiedAccountResponse) GetPerpetualTradingEnableUnifiedAccountResponse() *components.PerpetualTradingEnableUnifiedAccountResponse {
	if v == nil {
		return nil
	}
	return v.PerpetualTradingEnableUnifiedAccountResponse
}

// #region class-body-v2perpetualtradingenableunifiedaccountresponse
// #endregion class-body-v2perpetualtradingenableunifiedaccountresponse
