// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2RiskYieldDecreaseResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	RiskYieldLiquidityResponse *components.RiskYieldLiquidityResponse
}

func (v V2RiskYieldDecreaseResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2RiskYieldDecreaseResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2RiskYieldDecreaseResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2RiskYieldDecreaseResponse) GetRiskYieldLiquidityResponse() *components.RiskYieldLiquidityResponse {
	if v == nil {
		return nil
	}
	return v.RiskYieldLiquidityResponse
}

// #region class-body-v2riskyielddecreaseresponse
// #endregion class-body-v2riskyielddecreaseresponse
