// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2RiskYieldTokensChain string

const (
	V2RiskYieldTokensChainRobinhood V2RiskYieldTokensChain = "robinhood"
)

func (e V2RiskYieldTokensChain) ToPointer() *V2RiskYieldTokensChain {
	return &e
}
func (e *V2RiskYieldTokensChain) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "robinhood":
		*e = V2RiskYieldTokensChain(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V2RiskYieldTokensChain: %v", v)
	}
}

type V2RiskYieldTokensMinLiquidityUsdType string

const (
	V2RiskYieldTokensMinLiquidityUsdTypeNumber V2RiskYieldTokensMinLiquidityUsdType = "number"
	V2RiskYieldTokensMinLiquidityUsdTypeStr    V2RiskYieldTokensMinLiquidityUsdType = "str"
)

type V2RiskYieldTokensMinLiquidityUsd struct {
	Number *float64 `queryParam:"inline" union:"member"`
	Str    *string  `queryParam:"inline" union:"member"`

	Type V2RiskYieldTokensMinLiquidityUsdType
}

func CreateV2RiskYieldTokensMinLiquidityUsdNumber(number float64) V2RiskYieldTokensMinLiquidityUsd {
	typ := V2RiskYieldTokensMinLiquidityUsdTypeNumber

	return V2RiskYieldTokensMinLiquidityUsd{
		Number: &number,
		Type:   typ,
	}
}

func CreateV2RiskYieldTokensMinLiquidityUsdStr(str string) V2RiskYieldTokensMinLiquidityUsd {
	typ := V2RiskYieldTokensMinLiquidityUsdTypeStr

	return V2RiskYieldTokensMinLiquidityUsd{
		Str:  &str,
		Type: typ,
	}
}

func (u *V2RiskYieldTokensMinLiquidityUsd) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = V2RiskYieldTokensMinLiquidityUsd{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  V2RiskYieldTokensMinLiquidityUsdTypeNumber,
			Value: &number,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  V2RiskYieldTokensMinLiquidityUsdTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for V2RiskYieldTokensMinLiquidityUsd", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for V2RiskYieldTokensMinLiquidityUsd", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(V2RiskYieldTokensMinLiquidityUsdType)
	switch best.Type {
	case V2RiskYieldTokensMinLiquidityUsdTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case V2RiskYieldTokensMinLiquidityUsdTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for V2RiskYieldTokensMinLiquidityUsd", string(data))
}

func (u V2RiskYieldTokensMinLiquidityUsd) MarshalJSON() ([]byte, error) {
	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type V2RiskYieldTokensMinLiquidityUsd: all fields are null")
}

type TokenOrderBy string

const (
	TokenOrderByLiquidityUsd      TokenOrderBy = "liquidity_usd"
	TokenOrderByVolume24hUsd      TokenOrderBy = "volume_24h_usd"
	TokenOrderByMarketCapUsd      TokenOrderBy = "market_cap_usd"
	TokenOrderByPriceChange24hPct TokenOrderBy = "price_change_24h_pct"
	TokenOrderByCreatedAt         TokenOrderBy = "created_at"
)

func (e TokenOrderBy) ToPointer() *TokenOrderBy {
	return &e
}
func (e *TokenOrderBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "liquidity_usd":
		fallthrough
	case "volume_24h_usd":
		fallthrough
	case "market_cap_usd":
		fallthrough
	case "price_change_24h_pct":
		fallthrough
	case "created_at":
		*e = TokenOrderBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TokenOrderBy: %v", v)
	}
}

type V2RiskYieldTokensDirection string

const (
	V2RiskYieldTokensDirectionAsc  V2RiskYieldTokensDirection = "asc"
	V2RiskYieldTokensDirectionDesc V2RiskYieldTokensDirection = "desc"
)

func (e V2RiskYieldTokensDirection) ToPointer() *V2RiskYieldTokensDirection {
	return &e
}
func (e *V2RiskYieldTokensDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = V2RiskYieldTokensDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V2RiskYieldTokensDirection: %v", v)
	}
}

type V2RiskYieldTokensRequest struct {
	// The offset of the first item to return.
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// The number of items to return.
	Limit *int64                 `queryParam:"style=form,explode=true,name=limit"`
	Chain V2RiskYieldTokensChain `queryParam:"style=form,explode=true,name=chain"`
	// Filter to one kind of asset.
	Kind      optionalnullable.OptionalNullable[components.DexTokenKind] `queryParam:"style=form,explode=true,name=kind"`
	Launchpad optionalnullable.OptionalNullable[components.Launchpad]    `queryParam:"style=form,explode=true,name=launchpad"`
	// Matches symbol, name or stock ticker.
	Search optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=search"`
	// Only tokens the indexer can currently price.
	HasPrice        optionalnullable.OptionalNullable[bool]                             `queryParam:"style=form,explode=true,name=has_price"`
	StockTicker     optionalnullable.OptionalNullable[string]                           `queryParam:"style=form,explode=true,name=stock_ticker"`
	MinLiquidityUsd optionalnullable.OptionalNullable[V2RiskYieldTokensMinLiquidityUsd] `queryParam:"style=form,explode=true,name=min_liquidity_usd"`
	OrderBy         *TokenOrderBy                                                       `queryParam:"style=form,explode=true,name=order_by"`
	Direction       *V2RiskYieldTokensDirection                                         `queryParam:"style=form,explode=true,name=direction"`
}

func (v *V2RiskYieldTokensRequest) GetOffset() *int64 {
	if v == nil {
		return nil
	}
	return v.Offset
}

func (v *V2RiskYieldTokensRequest) GetLimit() *int64 {
	if v == nil {
		return nil
	}
	return v.Limit
}

func (v *V2RiskYieldTokensRequest) GetChain() V2RiskYieldTokensChain {
	if v == nil {
		return V2RiskYieldTokensChain("")
	}
	return v.Chain
}

func (v *V2RiskYieldTokensRequest) GetKind() optionalnullable.OptionalNullable[components.DexTokenKind] {
	if v == nil {
		return nil
	}
	return v.Kind
}

func (v *V2RiskYieldTokensRequest) GetLaunchpad() optionalnullable.OptionalNullable[components.Launchpad] {
	if v == nil {
		return nil
	}
	return v.Launchpad
}

func (v *V2RiskYieldTokensRequest) GetSearch() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.Search
}

func (v *V2RiskYieldTokensRequest) GetHasPrice() optionalnullable.OptionalNullable[bool] {
	if v == nil {
		return nil
	}
	return v.HasPrice
}

func (v *V2RiskYieldTokensRequest) GetStockTicker() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.StockTicker
}

func (v *V2RiskYieldTokensRequest) GetMinLiquidityUsd() optionalnullable.OptionalNullable[V2RiskYieldTokensMinLiquidityUsd] {
	if v == nil {
		return nil
	}
	return v.MinLiquidityUsd
}

func (v *V2RiskYieldTokensRequest) GetOrderBy() *TokenOrderBy {
	if v == nil {
		return nil
	}
	return v.OrderBy
}

func (v *V2RiskYieldTokensRequest) GetDirection() *V2RiskYieldTokensDirection {
	if v == nil {
		return nil
	}
	return v.Direction
}

// #region class-body-v2riskyieldtokensrequest
// #endregion class-body-v2riskyieldtokensrequest

type V2RiskYieldTokensResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	DexTokensResponse *components.DexTokensResponse
}

func (v V2RiskYieldTokensResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2RiskYieldTokensResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2RiskYieldTokensResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2RiskYieldTokensResponse) GetDexTokensResponse() *components.DexTokensResponse {
	if v == nil {
		return nil
	}
	return v.DexTokensResponse
}

// #region class-body-v2riskyieldtokensresponse
// #endregion class-body-v2riskyieldtokensresponse
