// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2TokenizedAssetsMarketsRequest struct {
	// Filter markets by category (e.g. 'tech', 'finance').
	Category optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=category"`
	// Case-insensitive substring match against the on-chain symbol, underlying ticker, and underlying name.
	Search optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=search"`
}

func (v *V2TokenizedAssetsMarketsRequest) GetCategory() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.Category
}

func (v *V2TokenizedAssetsMarketsRequest) GetSearch() optionalnullable.OptionalNullable[string] {
	if v == nil {
		return nil
	}
	return v.Search
}

// #region class-body-v2tokenizedassetsmarketsrequest
// #endregion class-body-v2tokenizedassetsmarketsrequest

type V2TokenizedAssetsMarketsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TokenizedAssetsMarketsListResponse *components.TokenizedAssetsMarketsListResponse
}

func (v V2TokenizedAssetsMarketsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2TokenizedAssetsMarketsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2TokenizedAssetsMarketsResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2TokenizedAssetsMarketsResponse) GetTokenizedAssetsMarketsListResponse() *components.TokenizedAssetsMarketsListResponse {
	if v == nil {
		return nil
	}
	return v.TokenizedAssetsMarketsListResponse
}

// #region class-body-v2tokenizedassetsmarketsresponse
// #endregion class-body-v2tokenizedassetsmarketsresponse
