// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2TokenizedAssetsOrderSubmitResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TokenizedAssetsSubmitOrderResponse *components.TokenizedAssetsSubmitOrderResponse
}

func (v V2TokenizedAssetsOrderSubmitResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2TokenizedAssetsOrderSubmitResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2TokenizedAssetsOrderSubmitResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2TokenizedAssetsOrderSubmitResponse) GetTokenizedAssetsSubmitOrderResponse() *components.TokenizedAssetsSubmitOrderResponse {
	if v == nil {
		return nil
	}
	return v.TokenizedAssetsSubmitOrderResponse
}

// #region class-body-v2tokenizedassetsordersubmitresponse
// #endregion class-body-v2tokenizedassetsordersubmitresponse
