// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2TokenizedAssetsPositionsRequest struct {
	// The address of the owner of the Tokenized Equities Account to get positions for. The account address is derived deterministically from this owner; balances are read from the derived account.
	Owner string `queryParam:"style=form,explode=true,name=owner"`
}

func (v *V2TokenizedAssetsPositionsRequest) GetOwner() string {
	if v == nil {
		return ""
	}
	return v.Owner
}

// #region class-body-v2tokenizedassetspositionsrequest
// #endregion class-body-v2tokenizedassetspositionsrequest

type V2TokenizedAssetsPositionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TokenizedAssetsPositionsResponse *components.TokenizedAssetsPositionsResponse
}

func (v V2TokenizedAssetsPositionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2TokenizedAssetsPositionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2TokenizedAssetsPositionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2TokenizedAssetsPositionsResponse) GetTokenizedAssetsPositionsResponse() *components.TokenizedAssetsPositionsResponse {
	if v == nil {
		return nil
	}
	return v.TokenizedAssetsPositionsResponse
}

// #region class-body-v2tokenizedassetspositionsresponse
// #endregion class-body-v2tokenizedassetspositionsresponse
