// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2TokenizedEquitiesOrderOrderHashCancelRequest struct {
	OrderHash string                                         `pathParam:"style=simple,explode=false,name=order_hash"`
	Body      components.TokenizedEquitiesCancelOrderRequest `request:"mediaType=application/json"`
}

func (v *V2TokenizedEquitiesOrderOrderHashCancelRequest) GetOrderHash() string {
	if v == nil {
		return ""
	}
	return v.OrderHash
}

func (v *V2TokenizedEquitiesOrderOrderHashCancelRequest) GetBody() components.TokenizedEquitiesCancelOrderRequest {
	if v == nil {
		return components.TokenizedEquitiesCancelOrderRequest{}
	}
	return v.Body
}

// #region class-body-v2tokenizedequitiesorderorderhashcancelrequest
// #endregion class-body-v2tokenizedequitiesorderorderhashcancelrequest

type V2TokenizedEquitiesOrderOrderHashCancelResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TokenizedEquitiesCancelOrderResponse *components.TokenizedEquitiesCancelOrderResponse
}

func (v V2TokenizedEquitiesOrderOrderHashCancelResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2TokenizedEquitiesOrderOrderHashCancelResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2TokenizedEquitiesOrderOrderHashCancelResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2TokenizedEquitiesOrderOrderHashCancelResponse) GetTokenizedEquitiesCancelOrderResponse() *components.TokenizedEquitiesCancelOrderResponse {
	if v == nil {
		return nil
	}
	return v.TokenizedEquitiesCancelOrderResponse
}

// #region class-body-v2tokenizedequitiesorderorderhashcancelresponse
// #endregion class-body-v2tokenizedequitiesorderorderhashcancelresponse
