// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2TokenizedAssetsQuoteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TokenizedAssetsQuoteResponse *components.TokenizedAssetsQuoteResponse
}

func (v V2TokenizedAssetsQuoteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2TokenizedAssetsQuoteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2TokenizedAssetsQuoteResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2TokenizedAssetsQuoteResponse) GetTokenizedAssetsQuoteResponse() *components.TokenizedAssetsQuoteResponse {
	if v == nil {
		return nil
	}
	return v.TokenizedAssetsQuoteResponse
}

// #region class-body-v2tokenizedassetsquoteresponse
// #endregion class-body-v2tokenizedassetsquoteresponse
