// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type V2TokenizedAssetsOrderOrderHashCancelRequest struct {
	OrderHash string                                       `pathParam:"style=simple,explode=false,name=order_hash"`
	Body      components.TokenizedAssetsCancelOrderRequest `request:"mediaType=application/json"`
}

func (v *V2TokenizedAssetsOrderOrderHashCancelRequest) GetOrderHash() string {
	if v == nil {
		return ""
	}
	return v.OrderHash
}

func (v *V2TokenizedAssetsOrderOrderHashCancelRequest) GetBody() components.TokenizedAssetsCancelOrderRequest {
	if v == nil {
		return components.TokenizedAssetsCancelOrderRequest{}
	}
	return v.Body
}

// #region class-body-v2tokenizedassetsorderorderhashcancelrequest
// #endregion class-body-v2tokenizedassetsorderorderhashcancelrequest

type V2TokenizedAssetsOrderOrderHashCancelResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TokenizedAssetsCancelOrderResponse *components.TokenizedAssetsCancelOrderResponse
}

func (v V2TokenizedAssetsOrderOrderHashCancelResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2TokenizedAssetsOrderOrderHashCancelResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2TokenizedAssetsOrderOrderHashCancelResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2TokenizedAssetsOrderOrderHashCancelResponse) GetTokenizedAssetsCancelOrderResponse() *components.TokenizedAssetsCancelOrderResponse {
	if v == nil {
		return nil
	}
	return v.TokenizedAssetsCancelOrderResponse
}

// #region class-body-v2tokenizedassetsorderorderhashcancelresponse
// #endregion class-body-v2tokenizedassetsorderorderhashcancelresponse
