// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package riskyield

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var riskYieldPoolsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "offset", FieldPath: "Offset", Kind: flagutil.FlagKindInt64, Optional: true, Description: "The offset of the first item to return."},
	{FlagName: "limit", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, Description: "The number of items to return."},
	{FlagName: "chain", Shorthand: "c", FieldPath: "Chain", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"robinhood"}, Description: "options: robinhood [required]"},
	{FlagName: "pair-class", Shorthand: "p", FieldPath: "PairClass", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=pair_class"`, Description: "What kind of pair a pool is, which is what the product is sorted by. (options: MEME_STOCK, STOCK_STABLE, STOCK_ETH, STOCK_STOCK, MEME_ETH, MEME_STABLE, ETH_STABLE, OTHER)"},
	{FlagName: "token", Shorthand: "t", FieldPath: "Token", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=token"`, Description: "Pools holding this token, on either side."},
	{FlagName: "stock-ticker", Shorthand: "s", FieldPath: "StockTicker", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=stock_ticker"`, Description: "string value"},
	{FlagName: "dex-version", FieldPath: "DexVersion", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=dex_version"`, Description: "Which Uniswap deployment a pool belongs to.\n\nv3 pools hold their own tokens and pay LPs the fee tier. v4 pools live in a\nshared PoolManager and may route the fee through a hook, which is where the\nlaunchpad pools' zero LP yield comes from. (options: V3, V4)"},
	{FlagName: "launchpad", FieldPath: "Launchpad", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=launchpad"`, Description: "options: PONS_V1, PONS_V2, POOLS_TRADE, BAGS"},
	{FlagName: "lp-earns-fees", FieldPath: "LpEarnsFees", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=lp_earns_fees"`, Description: "Leave unset to see everything. Set true to hide the pools whose hook keeps the fee — most of this chain's volume, and none of its yield."},
	{FlagName: "lp-open", FieldPath: "LpOpen", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=lp_open"`, Description: "Whether liquidity may be added at all."},
	{FlagName: "watched", Shorthand: "w", FieldPath: "Watched", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=watched"`, Description: "Only pools the indexer follows closely, which are the only ones with trailing metrics."},
	{FlagName: "min-tvl-usd", FieldPath: "MinTvlUsd", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: number | string)"}},
	{FlagName: "min-volume-24h-usd", FieldPath: "MinVolume24hUsd", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: number | string)"}},
	{FlagName: "order-by", FieldPath: "OrderBy", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"il_adjusted_apr_7d", "fee_apr_24h", "fee_apr_7d", "tvl_usd", "volume_24h_usd", "volume_7d_usd", "realized_vol_24h", "realized_vol_7d", "created_at"}, Description: "options: il_adjusted_apr_7d, fee_apr_24h, fee_apr_7d, tvl_usd, volume_24h_usd, volume_7d_usd, realized_vol_24h, realized_vol_7d, created_at"},
	{FlagName: "direction", FieldPath: "Direction", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"asc", "desc"}, Description: "options: asc, desc"},
}

// initRiskYieldPoolsCmd initializes the risk-yield-pools command.
func initRiskYieldPoolsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "risk-yield-pools",
		Short:   "List pools",
		Long:    "Pools you could provide liquidity to, ranked by what you would keep.\n\n**Read `lp_earns_fees` first.** The launchpad that dominates this chain\ngraduates tokens into pools whose hook takes the swap fee, so they trade\nenormously and pay an external liquidity provider nothing. Those pools are\nlisted — they carry the memecoin's price and volume — with a fee APR of\nexactly zero and a note saying why. Pass `lp_earns_fees=true` to hide them.\n\nThe default ordering is `il_adjusted_apr_7d`: the fee APR less the expected\nimpermanent-loss drag from the pair's own volatility. A pool paying 200% on\nan asset that moves 400% is not a better position than one paying 20% on an\nasset that moves 30%, and sorting on the raw APR would say it was.\n\nPools too thin for a rate to mean anything — under 20 swaps a day, or under\n$1,000 of liquidity — are served with `ranked: false` and always sort last.",
		Example: "  compass risk-yield risk-yield-pools --chain robinhood",
		RunE:    runRiskYieldPoolsCmd,
		Aliases: []string{"ryp"},
	}
	flagutil.RegisterFlags(cmd, riskYieldPoolsCmdMeta)
	if err := flagutil.ValidateMeta[operations.V2RiskYieldPoolsRequest](riskYieldPoolsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for risk-yield-pools: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runRiskYieldPoolsCmd executes the risk-yield-pools command.
func runRiskYieldPoolsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, riskYieldPoolsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, riskYieldPoolsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.V2RiskYieldPoolsRequest](cmd, riskYieldPoolsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.RiskYield.RiskYieldPools(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
