// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// Generated under the AGPL-3.0-only license.
// SPDX-License-Identifier: AGPL-3.0-only

package credit

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var rebalanceCmdMeta = []flagutil.FlagMeta{
	{FlagName: "owner", FieldPath: "Owner", Kind: flagutil.FlagKindString, Required: true, Description: "The address that owns the Credit Account. [required]"},
	{FlagName: "chain", Shorthand: "c", FieldPath: "Chain", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"arbitrum", "base", "bsc", "ethereum", "tempo"}, Description: "Blockchain network. Rebalance is not available on HyperEVM yet; use loop/unloop there. (options: arbitrum, base, bsc, ethereum, tempo) [required]"},
	{FlagName: "targets", Shorthand: "t", FieldPath: "Targets", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"targets"`, Description: "The positions to change. Scoped: only positions named here are touched; any position not listed is left untouched. [required]"},
	{FlagName: "max-slippage-percent", Shorthand: "m", FieldPath: "MaxSlippagePercent", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: number | string)"}},
	{FlagName: "gas-sponsorship", Shorthand: "g", FieldPath: "GasSponsorship", Kind: flagutil.FlagKindBool, Optional: true, Description: "If true, returns EIP-712 typed data for gas-sponsored execution instead of an unsigned transaction."},
}

// initRebalanceCmd initializes the rebalance command.
func initRebalanceCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "rebalance",
		Short:   "Rebalance the leveraged credit book",
		Long:    "Move one or more leveraged positions to the state you want, in ONE atomic\ntransaction.\n\nList the positions to change and the end state you want for each. The API\nworks out whether that means opening, growing, shrinking, delevering or\nclosing, and does them all together.\n\nMoney freed by shrinking or closing one position pays for growing or opening\nanother, so shifting funds between positions needs no new deposit. Any\nshortfall is taken from the Credit Account's idle balance, and the call\nreturns 422 if that does not cover it either.\n\nSee the [Leveraged Looping guide](https://docs.compasslabs.ai/v2/Products/Looping)\nfor protocol and chain coverage, capital routing and the full error list.",
		Example: "  compass credit rebalance --owner 0x4D3c07d1db7E4A9E44285fae9810d6549655bc74 --chain ethereum --targets '[{\"protocol\":\"AAVE\",\"collateral_token\":\"WETH\",\"borrow_token\":\"USDC\",\"target_multiplier\":2}]'",
		RunE:    runRebalanceCmd,
	}
	flagutil.RegisterFlags(cmd, rebalanceCmdMeta)
	if err := flagutil.ValidateMeta[components.CreditRebalanceRequest](rebalanceCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for rebalance: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runRebalanceCmd executes the rebalance command.
func runRebalanceCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, rebalanceCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, rebalanceCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.CreditRebalanceRequest](cmd, rebalanceCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Credit.Rebalance(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
