// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package credit

import (
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitCreditRoot(parent *cobra.Command) error {
	var CreditCmd = &cobra.Command{
		Use:   "credit",
		Short: "Operations for credit",
		Long:  "Operations for credit",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initCreditPositionsCmd(CreditCmd); err != nil {
		return err
	}

	if err := initCreditBalancesCmd(CreditCmd); err != nil {
		return err
	}

	if err := initCreditCreateAccountCmd(CreditCmd); err != nil {
		return err
	}

	if err := initCreditBorrowCmd(CreditCmd); err != nil {
		return err
	}

	if err := initCreditTransferCmd(CreditCmd); err != nil {
		return err
	}

	if err := initCreditRepayCmd(CreditCmd); err != nil {
		return err
	}

	if err := initCreditBundleCmd(CreditCmd); err != nil {
		return err
	}

	parent.AddCommand(CreditCmd)
	return nil
}
