// Tests for the unmanaged help helpers in overrides.go (not generated by Speakeasy).

package cli

import (
	"strings"
	"testing"

	"github.com/spf13/pflag"
)

// manageLikeFlags mirrors the flag shape the generator emits for
// `compass earn manage`: plain required flags plus one discriminated union.
func manageLikeFlags(t *testing.T) *pflag.FlagSet {
	t.Helper()
	fs := pflag.NewFlagSet("manage", pflag.ContinueOnError)
	fs.String("action", "", "Deposit or withdraw. (options: DEPOSIT, WITHDRAW) [required]")
	fs.String("amount", "", "Decimal amount.")
	fs.StringP("venue", "v", "", "JSON value (variants: AAVE: { token: string }, VAULT: { vault_address: string })")
	fs.String("venue.aave", "", "AaveVenue variant as JSON")
	fs.String("venue.aave.token", "", "The reserve token. [required]")
	fs.String("venue.vault", "", "VaultVenue variant as JSON")
	fs.String("venue.vault.vault-address", "", "The vault address. [required]")
	for _, name := range []string{"action", "venue.aave.token", "venue.vault.vault-address"} {
		if err := fs.SetAnnotation(name, "speakeasy:required", []string{"true"}); err != nil {
			t.Fatal(err)
		}
	}
	for _, name := range []string{"venue.aave", "venue.aave.token", "venue.vault", "venue.vault.vault-address"} {
		if err := fs.SetAnnotation(name, unionMemberAnnotation, []string{"venue"}); err != nil {
			t.Fatal(err)
		}
	}
	return fs
}

func TestUnionHelpSectionsClaimsUnionFlags(t *testing.T) {
	claimed, rendered := unionHelpSections(manageLikeFlags(t))
	for _, name := range []string{"venue", "venue.aave", "venue.aave.token", "venue.vault", "venue.vault.vault-address"} {
		if !claimed[name] {
			t.Errorf("expected %s to be claimed by the union section", name)
		}
	}
	if claimed["action"] || claimed["amount"] {
		t.Errorf("non-union flags must not be claimed: %v", claimed)
	}
	if !strings.HasPrefix(rendered, "\nVenue (pick ONE variant") {
		t.Fatalf("unexpected section header:\n%s", rendered)
	}
	if !strings.Contains(rendered, "[required with --venue.aave]") || !strings.Contains(rendered, "[required with --venue.vault]") {
		t.Fatalf("variant fields should name their variant:\n%s", rendered)
	}
	if strings.Contains(rendered, "[required]") {
		t.Fatalf("bare [required] must not survive inside a union section:\n%s", rendered)
	}
}

func TestUnionHelpSectionsNoUnions(t *testing.T) {
	fs := pflag.NewFlagSet("plain", pflag.ContinueOnError)
	fs.String("chain", "", "The chain. [required]")
	if claimed, rendered := unionHelpSections(fs); claimed != nil || rendered != "" {
		t.Fatalf("expected no sections, got %v / %q", claimed, rendered)
	}
}

func TestGroupedFlagUsagesKeepsVariantFieldsOutOfRequired(t *testing.T) {
	fs := manageLikeFlags(t)
	out := groupedFlagUsages(fs)
	required, rest, ok := strings.Cut(out, "\nVenue (pick ONE variant")
	if !ok {
		t.Fatalf("missing union section:\n%s", out)
	}
	if !strings.HasPrefix(required, "Required Flags:") || !strings.Contains(required, "--action") {
		t.Fatalf("required section should still list --action:\n%s", required)
	}
	if strings.Contains(required, "--venue") {
		t.Fatalf("variant fields leaked into Required Flags:\n%s", required)
	}
	if !strings.Contains(rest, "Optional Flags:") || !strings.Contains(rest, "--amount") {
		t.Fatalf("optional section should follow the union section:\n%s", rest)
	}
	if usage := fs.Lookup("venue.aave.token").Usage; !strings.HasSuffix(usage, "[required]") {
		t.Fatalf("rendering must not rewrite the live flag: %q", usage)
	}
}
