// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tokenizedequities

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var tokenizedEquitiesMarketsSymbolCmdMeta = []flagutil.FlagMeta{
	{FlagName: "symbol", Shorthand: "s", FieldPath: "Symbol", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "interval", Shorthand: "i", FieldPath: "Interval", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=interval"`, Description: "Optional candle interval. Must be paired with `range` and form a valid `(interval, range)` pair to include OHLC candles in the response. (options: 1min, 5min, 15min, 1hour, 4hour, 12hour, 1day)"},
	{FlagName: "range", Shorthand: "r", FieldPath: "Range", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=range"`, Description: "Optional lookback window. Must be paired with `interval` and form a valid `(interval, range)` pair to include OHLC candles in the response. (options: 1day, 1month, 3month, 6month, 1year, all)"},
}

// initTokenizedEquitiesMarketsSymbolCmd initializes the tokenized-equities-markets-symbol command.
func initTokenizedEquitiesMarketsSymbolCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "tokenized-equities-markets-symbol",
		Short:   "Get a single market",
		Long:    "Get extended detail for a single tokenized equity (e.g. `TSLAon`).\n\nIncludes 52-week range, volume, market cap, holder count, and tradable\nsessions in addition to the fields returned by `/markets`.\n\n**OHLC candles** are opt-in: pass both `interval` and `range` query\nparams to include a `candles` array in the response. They must be\nprovided together and must form one of the supported pairs:\n\n- `1min` / `5min` / `15min` with `range=1day`\n- `1hour` / `4hour` with `range=1month`\n- `12hour` with `range=3month`\n- `1day` with `range=3month` / `6month` / `1year` / `all`\n\nOmitting both returns the market detail without `candles`.",
		Example: "  compass tokenized-equities tokenized-equities-markets-symbol --symbol <value>",
		RunE:    runTokenizedEquitiesMarketsSymbolCmd,
		Aliases: []string{"tems"},
	}
	flagutil.RegisterFlags(cmd, tokenizedEquitiesMarketsSymbolCmdMeta)
	if err := flagutil.ValidateMeta[operations.V2TokenizedEquitiesMarketsSymbolRequest](tokenizedEquitiesMarketsSymbolCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for tokenized-equities-markets-symbol: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runTokenizedEquitiesMarketsSymbolCmd executes the tokenized-equities-markets-symbol command.
func runTokenizedEquitiesMarketsSymbolCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, tokenizedEquitiesMarketsSymbolCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, tokenizedEquitiesMarketsSymbolCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.V2TokenizedEquitiesMarketsSymbolRequest](cmd, tokenizedEquitiesMarketsSymbolCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.TokenizedEquities.TokenizedEquitiesMarketsSymbol(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
