// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tokenizedequities

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var tokenizedEquitiesPositionsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "owner", FieldPath: "Owner", Kind: flagutil.FlagKindString, Required: true, Description: "The address of the owner of the Tokenized Equities Account to get positions for. The account address is derived deterministically from this owner; balances are read from the derived account. [required]"},
}

// initTokenizedEquitiesPositionsCmd initializes the tokenized-equities-positions command.
func initTokenizedEquitiesPositionsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "tokenized-equities-positions",
		Short:   "Get tokenized-equity positions for an owner",
		Long:    "Get the tokenized-equity holdings for an owner.\n\nThe owner's Tokenized Equities Account address is derived deterministically\nfrom the `owner` query param; balances are read from that account (proceeds\nfrom filled orders settle there). The response returns the balance of every\nlisted tokenized equity, plus the latest USD price and a USD-valued balance\nwhen pricing is available. Zero balances are omitted, and a `total_usd`\naggregate is returned across all priced positions.\n\nReturns 400 `ACCOUNT_NOT_DEPLOYED` if the owner has no Tokenized Equities\nAccount deployed yet — create one via `/create_account` first.",
		Example: "  compass tokenized-equities tokenized-equities-positions --owner 0x29F20a192328eF1aD35e1564aBFf4Be9C5ce5f7B",
		RunE:    runTokenizedEquitiesPositionsCmd,
		Aliases: []string{"tep"},
	}
	flagutil.RegisterFlags(cmd, tokenizedEquitiesPositionsCmdMeta)
	if err := flagutil.ValidateMeta[operations.V2TokenizedEquitiesPositionsRequest](tokenizedEquitiesPositionsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for tokenized-equities-positions: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runTokenizedEquitiesPositionsCmd executes the tokenized-equities-positions command.
func runTokenizedEquitiesPositionsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, tokenizedEquitiesPositionsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, tokenizedEquitiesPositionsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.V2TokenizedEquitiesPositionsRequest](cmd, tokenizedEquitiesPositionsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.TokenizedEquities.TokenizedEquitiesPositions(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
