// This file is NOT generated by Speakeasy — it holds helpers (and types)
// called by the post-regen patches in cli-sdk/scripts/post-regen/01-output.patch
// and 02-pretty.patch. Speakeasy's regen does not touch files without the
// "Code generated by Speakeasy" header, so the helpers here survive on
// every regen automatically; only the call-site swaps in the patched
// generated files need re-application. See cli-sdk/PRESERVED_EDITS.md for
// the full architecture.

package output

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"reflect"
	"strconv"

	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

// normalizeForEncoding marshals content through the Speakeasy custom JSON
// marshaller (which honors `,omitzero` and unwraps `OptionalNullable[T]`
// from its `map[bool]*T` shape to the underlying scalar) and then unmarshals
// the result into a plain `any`. This is what YAML and TOON encoders should
// be fed — they look at raw struct tags and reflection otherwise, which
// produces broken output like `"apy_30d,omitzero": null` (TOON) or
// `name: {true: "Steakhouse..."}` (YAML).
func normalizeForEncoding(content any) (any, error) {
	if content == nil {
		return nil, nil
	}
	data, err := utils.MarshalJSON(content, "", true)
	if err != nil {
		// Fall back to encoding/json for content the Speakeasy marshaller can't
		// handle (e.g., types containing func fields). This is identical to the
		// fallback in marshalJSON() above.
		data, err = json.Marshal(content)
		if err != nil {
			return nil, fmt.Errorf("normalize: marshal: %w", err)
		}
	}
	// json.Unmarshal into `any` coerces every JSON number to float64, which
	// drops precision for integers above 2^53 — a real issue for raw DeFi
	// amounts (uint64 token balances, vault TVL, etc.) that frequently land
	// in that range. UseNumber() decodes numbers as json.Number (a string
	// alias) so we can convert them to int64 where they fit before encoding.
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	var out any
	if err := dec.Decode(&out); err != nil {
		return nil, fmt.Errorf("normalize: unmarshal: %w", err)
	}
	return numbersToGoTypes(out), nil
}

// numbersToGoTypes walks the decoded tree and replaces json.Number values
// with native Go numeric types — int64 for signed integer literals that fit,
// uint64 for positive literals that exceed int64 max but fit in uint64
// (typical for raw token amounts and vault TVL in wei), float64 otherwise.
// Without this step yaml.v3 and the TOON encoder render json.Number values
// as quoted strings (since the underlying type is string), which is visually
// wrong in a number context.
//
// The uint64 step matters in practice: ~9–18 ETH expressed in wei sits
// between 2^63 and 2^64, so vault TVLs and large balances would otherwise
// silently degrade to float64. Literals that exceed uint64 range fall back
// to float64 with the pre-UseNumber precision loss — no regression vs. the
// pre-fix behavior. We don't retain them as strings because YAML/TOON would
// quote them, which is strictly worse in a number context.
func numbersToGoTypes(v any) any {
	switch x := v.(type) {
	case json.Number:
		if i, err := x.Int64(); err == nil {
			return i
		}
		// Positive literals above int64 max but within uint64 range: keep
		// them as uint64 so the full integer precision survives YAML/TOON
		// encoding. Negative literals always fail this parse.
		if u, err := strconv.ParseUint(string(x), 10, 64); err == nil {
			return u
		}
		if f, err := x.Float64(); err == nil {
			return f
		}
		return string(x)
	case map[string]any:
		for k, val := range x {
			x[k] = numbersToGoTypes(val)
		}
		return x
	case []any:
		for i, val := range x {
			x[i] = numbersToGoTypes(val)
		}
		return x
	default:
		return v
	}
}

// errAlreadyPrinted is the sentinel wrapper returned by output.Error() so
// cmd/compass/main.go knows the user-visible error message has already been
// rendered and should NOT be reprinted via `fmt.Fprintln(os.Stderr, err)`.
// The exit-code intent is preserved by keeping the wrapped error non-nil.
type errAlreadyPrinted struct{ err error }

func (e *errAlreadyPrinted) Error() string { return e.err.Error() }
func (e *errAlreadyPrinted) Unwrap() error { return e.err }

// AlreadyPrinted wraps err in a marker type so callers (specifically
// cmd/compass/main.go) can detect that the friendly error rendering has
// already happened and suppress the default `fmt.Fprintln(os.Stderr, err)`.
// Callers that don't recognize the wrapper still get a working error value:
// .Error() returns the underlying message and errors.Is/As both work via
// Unwrap.
func AlreadyPrinted(err error) error {
	if err == nil {
		return nil
	}
	var marker *errAlreadyPrinted
	if errors.As(err, &marker) {
		return err
	}
	return &errAlreadyPrinted{err: err}
}

// IsAlreadyPrinted reports whether err (or any error in its chain) was
// returned from output.Error() and has therefore already been rendered to
// the user. main.go uses this to skip the default error print so the
// message isn't duplicated.
func IsAlreadyPrinted(err error) bool {
	if err == nil {
		return false
	}
	var marker *errAlreadyPrinted
	return errors.As(err, &marker)
}

// formatFastAPIDetail rewrites the FastAPI validation-error envelope
//
//	{"detail":[{"loc":["query","owner"],"msg":"…","type":"value_error"}, …]}
//
// into a flat human-readable list:
//
//	- query.owner: …
//
// Returns (formatted, true) when parsed matches that shape, otherwise
// (_, false) so the caller falls back to its default JSON-indent path.
// Duplicates (same loc + msg) are de-duped because FastAPI sometimes
// returns identical entries twice for the same validation failure.
func formatFastAPIDetail(parsed any) (string, bool) {
	m, ok := parsed.(map[string]any)
	if !ok {
		return "", false
	}
	detail, ok := m["detail"]
	if !ok || len(m) != 1 {
		// Not a {"detail": …}-only envelope — leave it alone so we don't
		// accidentally hide caller-defined error fields like "error" or
		// "message" that sit alongside detail.
		return "", false
	}
	entries, ok := detail.([]any)
	if !ok || len(entries) == 0 {
		return "", false
	}

	seen := make(map[string]struct{}, len(entries))
	var lines []string
	for _, raw := range entries {
		entry, ok := raw.(map[string]any)
		if !ok {
			return "", false // not the FastAPI shape — bail
		}
		msg, _ := entry["msg"].(string)
		if msg == "" {
			return "", false
		}
		// loc is a heterogeneous array like ["query","owner"] or
		// ["body","actions",0,"amount"]. Join with dots and stringify
		// each part with fmt.Sprint to keep ints readable.
		locParts, _ := entry["loc"].([]any)
		path := "request"
		if len(locParts) > 0 {
			parts := make([]string, len(locParts))
			for i, p := range locParts {
				parts[i] = fmt.Sprint(p)
			}
			path = joinDots(parts)
		}
		line := fmt.Sprintf("  - %s: %s", path, msg)
		if _, dup := seen[line]; dup {
			continue
		}
		seen[line] = struct{}{}
		lines = append(lines, line)
	}
	if len(lines) == 0 {
		return "", false
	}
	header := "Validation error:"
	if len(lines) > 1 {
		header = "Validation errors:"
	}
	return header + "\n" + joinLines(lines), true
}

func joinDots(parts []string) string {
	out := ""
	for i, p := range parts {
		if i > 0 {
			out += "."
		}
		out += p
	}
	return out
}

func joinLines(lines []string) string {
	out := ""
	for i, l := range lines {
		if i > 0 {
			out += "\n"
		}
		out += l
	}
	return out
}

// errorStatusCodeFromHTTPMeta extracts the HTTP status code from typed
// SDK errors (e.g. HTTPValidationError) that don't expose a `StatusCode`
// field directly but carry it on a nested `HTTPMeta.Response.StatusCode`.
// Returns 0 when neither shape matches.
//
// extractErrorStatusCode in output.go only looks at top-level fields, so
// without this helper FastAPI 422 errors print as "Error: …" instead of
// "API Error (HTTP 422): …".
func errorStatusCodeFromHTTPMeta(err error) int {
	if err == nil {
		return 0
	}
	v := reflect.ValueOf(err)
	for v.Kind() == reflect.Ptr || v.Kind() == reflect.Interface {
		if v.IsNil() {
			return 0
		}
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		return 0
	}
	meta := v.FieldByName("HTTPMeta")
	if !meta.IsValid() || meta.Kind() != reflect.Struct {
		return 0
	}
	resp := meta.FieldByName("Response")
	if !resp.IsValid() {
		return 0
	}
	for resp.Kind() == reflect.Ptr || resp.Kind() == reflect.Interface {
		if resp.IsNil() {
			return 0
		}
		resp = resp.Elem()
	}
	if resp.Kind() != reflect.Struct {
		return 0
	}
	sc := resp.FieldByName("StatusCode")
	if !sc.IsValid() || sc.Kind() != reflect.Int {
		return 0
	}
	return int(sc.Int())
}
