// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package globalmarketsperps

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var globalMarketsPerpsCandlesCmdMeta = []flagutil.FlagMeta{
	{FlagName: "symbol", FieldPath: "Symbol", Kind: flagutil.FlagKindString, Required: true, Description: "Asset ticker (e.g. AAPL, GOLD, EUR). The xyz: HIP-3 DEX prefix is added server-side if not already present. [required]"},
	{FlagName: "interval", Shorthand: "i", FieldPath: "Interval", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"1m", "5m", "15m", "1h", "4h", "1d", "1w"}, Description: "Candle interval: 1m, 5m, 15m, 1h, 4h, 1d, 1w (options: 1m, 5m, 15m, 1h, 4h, 1d, 1w) [required]"},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, Description: "Number of candles to return (max 5000, capped by Hyperliquid)."},
	{FlagName: "start-time", FieldPath: "StartTime", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=start_time"`, Description: "Optional start of the candle window in unix milliseconds. If omitted, computed as end_time - limit * interval."},
	{FlagName: "end-time", Shorthand: "e", FieldPath: "EndTime", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=end_time"`, Description: "Optional end of the candle window in unix milliseconds. Defaults to now."},
}

// initGlobalMarketsPerpsCandlesCmd initializes the global-markets-perps-candles command.
func initGlobalMarketsPerpsCandlesCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "global-markets-perps-candles",
		Short:   "Get OHLCV candles",
		Long:    "Return OHLCV candles for a single asset and interval.\n\nWraps Hyperliquid's ``candleSnapshot`` info type and adds the xyz: HIP-3 DEX\nprefix server-side so the SDK only needs the bare ticker (e.g. ``AAPL``).\nCandle ``time`` is returned in unix seconds, ready for TradingView\nlightweight-charts. Cached for 15 seconds per (symbol, interval, window).",
		Example: "  compass global-markets-perps global-markets-perps-candles --symbol AAPL --interval 1h",
		RunE:    runGlobalMarketsPerpsCandlesCmd,
		Aliases: []string{"gmpc"},
	}
	flagutil.RegisterFlags(cmd, globalMarketsPerpsCandlesCmdMeta)
	if err := flagutil.ValidateMeta[operations.V2GlobalMarketsPerpsCandlesRequest](globalMarketsPerpsCandlesCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for global-markets-perps-candles: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGlobalMarketsPerpsCandlesCmd executes the global-markets-perps-candles command.
func runGlobalMarketsPerpsCandlesCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, globalMarketsPerpsCandlesCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, globalMarketsPerpsCandlesCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.V2GlobalMarketsPerpsCandlesRequest](cmd, globalMarketsPerpsCandlesCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.GlobalMarketsPerps.GlobalMarketsPerpsCandles(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
