// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package globalmarketsperps

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var marketOrderCmdMeta = []flagutil.FlagMeta{
	{FlagName: "owner", FieldPath: "Owner", Kind: flagutil.FlagKindString, Required: true, Description: "Owner of the global markets perps product account [required]"},
	{FlagName: "asset", Shorthand: "a", FieldPath: "Asset", Kind: flagutil.FlagKindString, Required: true, Description: "Asset ticker symbol (e.g. AAPL, GOLD, EUR) [required]"},
	{FlagName: "side", FieldPath: "Side", Kind: flagutil.FlagKindString, Required: true, Description: "Order side: 'buy' or 'sell' [required]"},
	{FlagName: "size", FieldPath: "Size", Kind: flagutil.FlagKindString, Required: true, Description: "Number of contracts (human-readable) [required]"},
	{FlagName: "slippage-percent", FieldPath: "SlippagePercent", Kind: flagutil.FlagKindFloat64, Optional: true, Description: "Max slippage percentage for price protection"},
	{FlagName: "reduce-only", Shorthand: "r", FieldPath: "ReduceOnly", Kind: flagutil.FlagKindBool, Optional: true, Description: "If true, order can only reduce an existing position"},
	{FlagName: "builder", Shorthand: "b", FieldPath: "Builder", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"builder,omitempty"`, Description: "Optional builder fee. When provided, the order action carries the builder address and fee — the end-user must have already approved this builder via /approve_builder_fee up to at least this rate. Omit (or pass null) to place the order with no builder fee."},
}

// initMarketOrderCmd initializes the market-order command.
func initMarketOrderCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "market-order",
		Short:   "Place market order",
		Long:    "Prepare a market order on a global markets perps market.\n\nReturns EIP-712 typed data for the user to sign. After signing, submit\nthe signature via the /execute endpoint. Executes as an IOC order at the\ncurrent mark price with slippage protection.",
		Example: "  compass global-markets-perps market-order --owner 0x06A9aF046187895AcFc7258450B15397CAc67400 --asset AAPL --side buy --size 10.0",
		RunE:    runMarketOrderCmd,
		Aliases: []string{"mo"},
	}
	flagutil.RegisterFlags(cmd, marketOrderCmdMeta)
	if err := flagutil.ValidateMeta[components.GlobalMarketsPerpsMarketOrderRequest](marketOrderCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for market-order: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runMarketOrderCmd executes the market-order command.
func runMarketOrderCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, marketOrderCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, marketOrderCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.GlobalMarketsPerpsMarketOrderRequest](cmd, marketOrderCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.GlobalMarketsPerps.MarketOrder(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
