// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package globalmarketsperps

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var withdrawCmdMeta = []flagutil.FlagMeta{
	{FlagName: "owner", FieldPath: "Owner", Kind: flagutil.FlagKindString, Required: true, Description: "The user's EOA address (owner of the global markets perps account) [required]"},
	{FlagName: "amount", Shorthand: "a", FieldPath: "Amount", Kind: flagutil.FlagKindString, Required: true, Description: "USDC amount to withdraw (human-readable, e.g. '500.0') [required]"},
	{FlagName: "destination", FieldPath: "Destination", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"destination,omitempty"`, Description: "Arbitrum destination address (defaults to owner if not specified)"},
}

// initWithdrawCmd initializes the withdraw command.
func initWithdrawCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "withdraw",
		Short:   "Withdraw USDC from global markets perps account",
		Long:    "Prepare a USDC withdrawal from Hyperliquid to Arbitrum.\n\nReturns EIP-712 typed data for the user to sign. After signing, submit\nthe signature via the /execute endpoint. Withdrawal processing takes\nminutes to hours depending on bridge conditions.",
		Example: "  compass global-markets-perps withdraw --owner 0x06A9aF046187895AcFc7258450B15397CAc67400 --amount 100.0",
		RunE:    runWithdrawCmd,
	}
	flagutil.RegisterFlags(cmd, withdrawCmdMeta)
	if err := flagutil.ValidateMeta[components.GlobalMarketsPerpsWithdrawRequest](withdrawCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for withdraw: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runWithdrawCmd executes the withdraw command.
func runWithdrawCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, withdrawCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, withdrawCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.GlobalMarketsPerpsWithdrawRequest](cmd, withdrawCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.GlobalMarketsPerps.Withdraw(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
