// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package earn

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var pendleMarketsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "order-by", FieldPath: "OrderBy", Kind: flagutil.FlagKindString, Required: true, Description: "The field to order the results by. [required]"},
	{FlagName: "direction", FieldPath: "Direction", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"asc", "desc"}, Description: "The direction to order the results by. (options: asc, desc)"},
	{FlagName: "offset", FieldPath: "Offset", Kind: flagutil.FlagKindInt64, Optional: true, Description: "The offset of the first item to return."},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, Description: "The number of items to return."},
	{FlagName: "chain", Shorthand: "c", FieldPath: "Chain", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=chain"`, Description: "Optional chain filter. If not provided, returns markets for all chains. (options: base, ethereum, arbitrum, hyperevm)"},
	{FlagName: "underlying-symbol", Shorthand: "u", FieldPath: "UnderlyingSymbol", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=underlying_symbol"`, Description: "Filter markets by underlying asset symbol (e.g., 'USDC', 'WETH')."},
	{FlagName: "min-tvl-usd", Shorthand: "m", FieldPath: "MinTvlUsd", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: number | string)"}},
}

// initPendleMarketsCmd initializes the pendle-markets command.
func initPendleMarketsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "pendle-markets",
		Short:   "List pendle markets",
		Long:    "List Pendle yield trading markets with TVL and implied APY.\n\nReturns Pendle market data including Principal Token (PT), Standardized Yield (SY),\nand Yield Token (YT) addresses, along with market expiry, TVL, and implied APY.\n\nUse this endpoint to discover yield trading opportunities, compare rates across\nPendle markets, or build market selection interfaces.\n\nAPY values are returned in percentage format (e.g., 5.25 means 5.25%). Markets\nwithout complete metadata or statistics are excluded.",
		Example: "  compass earn pendle-markets --order-by tvl_usd",
		RunE:    runPendleMarketsCmd,
		Aliases: []string{"pm"},
	}
	flagutil.RegisterFlags(cmd, pendleMarketsCmdMeta)
	if err := flagutil.ValidateMeta[operations.V2EarnPendleMarketsRequest](pendleMarketsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for pendle-markets: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runPendleMarketsCmd executes the pendle-markets command.
func runPendleMarketsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, pendleMarketsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, pendleMarketsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.V2EarnPendleMarketsRequest](cmd, pendleMarketsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Earn.PendleMarkets(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
