// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package earn

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var transferCmdMeta = []flagutil.FlagMeta{
	{FlagName: "owner", FieldPath: "Owner", Kind: flagutil.FlagKindString, Required: true, Description: "The owner's wallet address. [required]"},
	{FlagName: "chain", Shorthand: "c", FieldPath: "Chain", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"base", "ethereum", "arbitrum", "hyperevm", "tempo"}, Description: "The chain to use. (options: base, ethereum, arbitrum, hyperevm, tempo) [required]"},
	{FlagName: "token", Shorthand: "t", FieldPath: "Token", Kind: flagutil.FlagKindString, Required: true, Description: "The token you would like to transfer. [required]"},
	{FlagName: "amount", FieldPath: "Amount", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, TypeDescription: "JSON value (one of: number | string)"}},
	{FlagName: "action", FieldPath: "Action", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"DEPOSIT", "WITHDRAW"}, Description: "Whether you are depositing to or withdrawing from your earn account. (options: DEPOSIT, WITHDRAW) [required]"},
	{FlagName: "gas-sponsorship", Shorthand: "g", FieldPath: "GasSponsorship", Kind: flagutil.FlagKindBool, Optional: true, Description: "Optionally request gas sponsorship. If set to `true`, EIP-712 signature data will be returned that must be signed by the `owner` and submitted to the `/gas_sponsorship/prepare` endpoint."},
	{FlagName: "spender", Shorthand: "s", FieldPath: "Spender", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"spender,omitempty"`, Description: "The address that will call Permit2's permitTransferFrom to execute the transfer. When `action` is 'DEPOSIT' and `gas_sponsorship` is `true`: - If provided, the signature will authorize this address (typically a gas sponsor) to pull tokens. - If not provided, defaults to the Earn Account (Safe) address, allowing the transfer to be included in a bundle transaction where the Safe pulls the tokens itself."},
	{FlagName: "recipient", Shorthand: "r", FieldPath: "Recipient", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"recipient,omitempty"`, Description: "Optional recipient address for withdrawals. When `action` is 'WITHDRAW': - If provided, tokens will be sent to this address instead of the owner. - If not provided, defaults to the owner's address. "},
}

// initTransferCmd initializes the transfer command.
func initTransferCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "transfer",
		Short:   "Transfer tokens to/from account",
		Long:    "Transfer tokens between an owner's wallet and their Earn Account.\n\nUse `DEPOSIT` to move tokens from the owner's wallet into their Earn Account. Use `WITHDRAW` to move tokens from the Earn Account back to the owner's wallet.\n\n**Gas-sponsored deposits** require two steps:\n\n**Step 1 (once per token):** Set up Permit2 allowance\n1. Call [/gas_sponsorship/approve_transfer](https://docs.compasslabs.ai/v2/api-reference/gas-sponsorship/approve-token-transfer) to get EIP-712 typed data\n2. Owner signs the typed data\n3. Submit signature + typed data to [/gas_sponsorship/prepare](https://docs.compasslabs.ai/v2/api-reference/gas-sponsorship/prepare-gas-sponsored-transaction)\n\n**Step 2 (each transfer):** Execute the gas-sponsored transfer\n1. Call this endpoint with `gas_sponsorship=true` to get EIP-712 typed data\n2. Owner signs the typed data\n3. Submit signature + typed data to [/gas_sponsorship/prepare](https://docs.compasslabs.ai/v2/api-reference/gas-sponsorship/prepare-gas-sponsored-transaction)\n\n**Note:** This endpoint moves tokens to/from the Earn Account itself—not into yield venues. To deposit into a vault or Aave market, use the [manage endpoint](https://docs.compasslabs.ai/v2/api-reference/earn/manage-earn-position).",
		Example: "  compass earn transfer --owner 0x01E62835dd7F52173546A325294762143eE4a882 --chain base --token USDC --amount 0.01 --action DEPOSIT",
		RunE:    runTransferCmd,
	}
	flagutil.RegisterFlags(cmd, transferCmdMeta)
	if err := flagutil.ValidateMeta[components.EarnTransferRequest](transferCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for transfer: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runTransferCmd executes the transfer command.
func runTransferCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, transferCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, transferCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.EarnTransferRequest](cmd, transferCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Earn.Transfer(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
