// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tokenizedassets

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var marketsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "category", FieldPath: "Category", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter markets by category (e.g. 'tech', 'finance')."},
	{FlagName: "search", Shorthand: "s", FieldPath: "Search", Kind: flagutil.FlagKindString, Optional: true, Description: "Case-insensitive substring match against the on-chain symbol, underlying ticker, and underlying name."},
	{FlagName: "provider", Shorthand: "p", FieldPath: "Provider", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"ondo", "midas", "ixs", "centrifuge", "wisdomtree"}, Description: "Filter by issuer ('ondo' equities, 'midas' RWA yield). (options: ondo, midas, ixs, centrifuge, wisdomtree)"},
	{FlagName: "asset-class", Shorthand: "a", FieldPath: "AssetClass", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"EQUITY", "T_BILLS", "BASIS_TRADE", "BTC_YIELD", "MANAGED_VAULT", "DERWA", "MONEY_MARKET"}, Description: "Filter by asset class (EQUITY, T_BILLS, BASIS_TRADE, BTC_YIELD). (options: EQUITY, T_BILLS, BASIS_TRADE, BTC_YIELD, MANAGED_VAULT, DERWA, MONEY_MARKET)"},
	{FlagName: "chain", FieldPath: "Chain", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"base", "ethereum", "arbitrum", "hyperevm", "tempo", "bsc", "robinhood", "ethereum_sepolia"}, Description: "Filter by network. Equities are Ethereum-only; RWA yield assets exist on Ethereum and Base. (options: base, ethereum, arbitrum, hyperevm, tempo, bsc, robinhood, ethereum_sepolia)"},
}

// initMarketsCmd initializes the markets command.
func initMarketsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "markets",
		Short:   "List markets",
		Long:    "List the tradable tokenized-asset catalog.\n\nAggregates all four providers — Ondo (tokenized US equities), Midas (RWA\nyield tokens), IXS (managed vaults), and Centrifuge (deRWA wrappers) — into\na single list with live USD pricing, plus APY and TVL for yield assets.\nFilter by provider, asset class, or chain, and narrow the results with a\nsector `category` or free-text `search`.",
		Example: "  compass tokenized-assets markets",
		Args:    cobra.NoArgs,
		RunE:    runMarketsCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "v2_tokenized_assets_markets",
		},
	}
	flagutil.RegisterFlags(cmd, marketsCmdMeta)
	if err := flagutil.ValidateMeta[operations.V2TokenizedAssetsMarketsRequest](marketsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for markets: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runMarketsCmd executes the markets command.
func runMarketsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.V2TokenizedAssetsMarketsRequest](cmd, marketsCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.TokenizedAssets.Markets(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
