// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// Generated under the AGPL-3.0-only license.
// SPDX-License-Identifier: AGPL-3.0-only

package tokenizedassets

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var orderChargeFeeCmdMeta = []flagutil.FlagMeta{
	{FlagName: "order-hash", FieldPath: "OrderHash", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "owner", FieldPath: "Body.Owner", Kind: flagutil.FlagKindString, Required: true, Description: "The owner's wallet address; the product account is derived from it. [required]"},
	{FlagName: "fee", Shorthand: "f", FieldPath: "Body.Fee", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"fee"`, Description: "Fee configuration for tokenized-asset trades.\n\nSame shape as `Fee`, but narrows `denomination` to the values supported by\ntokenized-asset trades. PERFORMANCE is not supported because realized-profit\nfees are not computed for spot buy/sell trades. [required]"},
	{FlagName: "gas-sponsorship", Shorthand: "g", FieldPath: "Body.GasSponsorship", Kind: flagutil.FlagKindBool, Optional: true, Description: "When true, returns an EIP-712 payload for gas-sponsored execution instead of an unsigned transaction."},
}

// initOrderChargeFeeCmd initializes the order-charge-fee command.
func initOrderChargeFeeCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "order-charge-fee",
		Short:   "Charge a partner fee",
		Long:    "Charge a partner fee on a filled equity sell order's USDC proceeds.\n\nEquity orders settle off-chain, so fees can't be bundled into the trade — call\nthis after a sell fills and it builds a USDC transfer of your `fee` from the\nactual proceeds, executed by the product account (owner signs, or EIP-712 with\n`gas_sponsorship`).",
		Example: "  compass tokenized-assets order-charge-fee --order-hash <value> --owner <value> --fee '{\"recipient\":\"<value>\",\"amount\":8619.46,\"denomination\":\"PERCENTAGE\"}'",
		RunE:    runOrderChargeFeeCmd,
		Aliases: []string{"ocf"},
	}
	flagutil.RegisterFlags(cmd, orderChargeFeeCmdMeta)
	if err := flagutil.ValidateMeta[operations.V2TokenizedAssetsOrderOrderHashChargeFeeRequest](orderChargeFeeCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for order-charge-fee: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runOrderChargeFeeCmd executes the order-charge-fee command.
func runOrderChargeFeeCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, orderChargeFeeCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, orderChargeFeeCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.V2TokenizedAssetsOrderOrderHashChargeFeeRequest](cmd, orderChargeFeeCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.TokenizedAssets.OrderChargeFee(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
