// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// Generated under the AGPL-3.0-only license.
// SPDX-License-Identifier: AGPL-3.0-only

package tokenizedassets

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var orderCmdMeta = []flagutil.FlagMeta{
	{FlagName: "from-token", Shorthand: "f", FieldPath: "FromToken", Kind: flagutil.FlagKindString, Required: true, Description: "Token the sender is paying. Either an on-chain symbol (e.g. `TSLAon`), the literal `USDC`, or a 0x-prefixed token address. [required]"},
	{FlagName: "to-token", Shorthand: "t", FieldPath: "ToToken", Kind: flagutil.FlagKindString, Required: true, Description: "Token the sender is receiving. Same accepted forms as `from_token`. [required]"},
	{FlagName: "amount", Shorthand: "a", FieldPath: "Amount", Kind: flagutil.FlagKindString, Required: true, Description: "Human-readable amount of `from_token` to swap (decimal string). Decimals are applied server-side. [required]"},
	{FlagName: "owner", FieldPath: "Owner", Kind: flagutil.FlagKindString, Required: true, Description: "Wallet that owns the Tokenized Assets Account. The product account address is derived deterministically from this owner. The owner signs the EIP-712 payloads returned by this endpoint (the optional approval and the order itself). [required]"},
	{FlagName: "slippage-bps", Shorthand: "s", FieldPath: "SlippageBps", Kind: flagutil.FlagKindInt64, Optional: true, Description: "Max acceptable slippage in basis points (1 bp = 0.01%). Range 1-5000 (0.01%-50%); defaults to 50 (0.5%). The upper bound is intentionally wide so callers can clear the wide auction floors quoted for thinly-traded tokenized stocks."},
}

// initOrderCmd initializes the order command.
func initOrderCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "order",
		Short:   "Build an order",
		Long:    "Build a tokenized-**equity** (Ondo) buy/sell order; the product account is the\nmaker.\n\nReturns everything needed to place the order in one round-trip: a price quote,\na one-time token approval to sign (only until the settlement contract is\napproved), and the order payload the owner signs off-chain. Only the approval\never touches the chain — the signed order is relayed to market makers, never\nbroadcast. Equities only; RWA yield tokens use `/transact/buy` and\n`/transact/sell`.",
		Example: "  compass tokenized-assets order --from-token <value> --to-token <value> --amount 853.30 --owner <value>",
		RunE:    runOrderCmd,
	}
	flagutil.RegisterFlags(cmd, orderCmdMeta)
	if err := flagutil.ValidateMeta[components.TokenizedAssetsBuildOrderRequest](orderCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for order: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runOrderCmd executes the order command.
func runOrderCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, orderCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, orderCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.TokenizedAssetsBuildOrderRequest](cmd, orderCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.TokenizedAssets.Order(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
