// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tokenizedassets

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var redemptionsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "owner", FieldPath: "Owner", Kind: flagutil.FlagKindString, Required: true, Description: "The owner of the Tokenized Assets Account whose IXS redemption requests to read. Requests are reconstructed on-chain from the derived product account (the request receiver). [required]"},
	{FlagName: "chain", Shorthand: "c", FieldPath: "Chain", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"base", "ethereum", "arbitrum", "hyperevm", "tempo", "bsc"}, Description: "Network the IXS vault lives on (IXS managed vaults are on BNB Smart Chain). (options: base, ethereum, arbitrum, hyperevm, tempo, bsc)"},
	{FlagName: "vault", Shorthand: "v", FieldPath: "Vault", Kind: flagutil.FlagKindString, Optional: true, Description: "The IXS vault handle to read redemptions for (e.g. 'ixv1')."},
}

// initRedemptionsCmd initializes the redemptions command.
func initRedemptionsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "redemptions",
		Short:   "Get IXS vault redemption requests for an owner",
		Long:    "Get an owner's IXS vault redemption requests (async redemption status).\n\nIXS managed-vault **sells** are asynchronous: `/transact/sell` returns a\n`requestRedeem` transaction, and the vault operator settles it off-chain\nlater. This endpoint reconstructs the owner's requests directly from the\nvault on every call (Compass persists no async state) — each entry carries\nits `status` (`pending` | `finalized` | `rejected`), the `shares` requested,\nand, while `pending`, the `expected_net_assets` it would settle for at the\ncurrent NAV (a preview, not a guarantee).\n\nIXS vaults live on BNB Smart Chain — pass `chain=bsc` (the default) and the\n`vault` handle (default `ixv1`).",
		Example: "  compass tokenized-assets redemptions --owner 0x29F20a192328eF1aD35e1564aBFf4Be9C5ce5f7B",
		RunE:    runRedemptionsCmd,
	}
	flagutil.RegisterFlags(cmd, redemptionsCmdMeta)
	if err := flagutil.ValidateMeta[operations.V2TokenizedAssetsRedemptionsRequest](redemptionsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for redemptions: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runRedemptionsCmd executes the redemptions command.
func runRedemptionsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, redemptionsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, redemptionsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.V2TokenizedAssetsRedemptionsRequest](cmd, redemptionsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.TokenizedAssets.Redemptions(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
