// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tokenizedassets

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var sellCmdMeta = []flagutil.FlagMeta{
	{FlagName: "token-in", FieldPath: "TokenIn", Kind: flagutil.FlagKindString, Required: true, Description: "Token to spend. For a buy this must be a stablecoin the Midas issuance vault accepts (USDC on every supported network; mBASIS also accepts USDT/DAI on Ethereum). For a sell it is the Midas RWA asset to redeem (e.g. 'mTBILL'). [required]"},
	{FlagName: "token-out", FieldPath: "TokenOut", Kind: flagutil.FlagKindString, Required: true, Description: "Token to receive. For a buy this is the Midas RWA asset to mint (e.g. 'mTBILL'); for a sell it is the payout stablecoin (USDC). [required]"},
	{FlagName: "amount-in", Shorthand: "a", FieldPath: "AmountIn", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, TypeDescription: "JSON value (one of: number | string)"}},
	{FlagName: "slippage", Shorthand: "s", FieldPath: "Slippage", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: number | string)"}},
	{FlagName: "owner", FieldPath: "Owner", Kind: flagutil.FlagKindString, Required: true, Description: "The owner's wallet address. [required]"},
	{FlagName: "chain", Shorthand: "c", FieldPath: "Chain", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"base", "ethereum", "arbitrum", "hyperevm", "tempo"}, Description: "The chain to use. (options: base, ethereum, arbitrum, hyperevm, tempo) [required]"},
	{FlagName: "gas-sponsorship", Shorthand: "g", FieldPath: "GasSponsorship", Kind: flagutil.FlagKindBool, Optional: true, Description: "When true, returns an EIP-712 payload for gas-sponsored execution instead of an unsigned transaction."},
}

// initSellCmd initializes the sell command.
func initSellCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "sell",
		Short:   "Sell an RWA yield token (Midas: mTBILL/mBASIS/mBTC)",
		Long:    "Sell (redeem) an RWA yield asset (e.g. `mTBILL`) inside the product account.\n\nRedeems `token_in` (a Midas RWA asset held by the Tokenized Assets Account)\ndirectly with Midas into `token_out` (USDC). Returns an unsigned transaction\nfor the owner to sign, or an EIP-712 payload when `gas_sponsorship` is true.\n\nInstant redemption draws on Midas's on-chain liquidity and is subject to a\nsmall redemption fee and daily limit.",
		Example: "  compass tokenized-assets sell --token-in <value> --token-out <value> --amount-in 8512.47 --owner <value> --chain ethereum",
		RunE:    runSellCmd,
	}
	flagutil.RegisterFlags(cmd, sellCmdMeta)
	if err := flagutil.ValidateMeta[components.TokenizedAssetsTradeRequest](sellCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for sell: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runSellCmd executes the sell command.
func runSellCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, sellCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, sellCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.TokenizedAssetsTradeRequest](cmd, sellCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.TokenizedAssets.Sell(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
