// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tokenizedassets

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var tokenizedAssetsOrderSubmitCmdMeta = []flagutil.FlagMeta{
	{FlagName: "signed-order", FieldPath: "SignedOrder", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"signed_order"`, Description: "The order struct returned by `/order` (`order.order_message`). `maker` is the Tokenized Assets Account, not the owner's wallet — pass this dict back to the API verbatim. [required]"},
	{FlagName: "signature", FieldPath: "Signature", Kind: flagutil.FlagKindString, Required: true, Description: "Owner's EIP-712 signature over `order.safe_message_eip712` from the `/order` response. The signature is validated against the Tokenized Equities Account at fill time, so it must be a signature over the typed-data hash, not the raw order hash. [required]"},
	{FlagName: "extension", Shorthand: "e", FieldPath: "Extension", Kind: flagutil.FlagKindString, Required: true, Description: "Opaque hex blob from the `/order` response — pass back unchanged. [required]"},
	{FlagName: "quote-id", FieldPath: "QuoteID", Kind: flagutil.FlagKindString, Required: true, Description: "`order.quote_id` from the `/order` response — pass back unchanged. [required]"},
	{FlagName: "order-hash", FieldPath: "OrderHash", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"order_hash,omitempty"`, Description: "`order.order_hash` from the `/order` response. Optional but recommended: the upstream relayer occasionally returns a 2xx with an empty body, and supplying the hash lets the API still return a usable handle for status and cancel lookups instead of failing."},
}

// initTokenizedAssetsOrderSubmitCmd initializes the tokenized-assets-order-submit command.
func initTokenizedAssetsOrderSubmitCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "tokenized-assets-order-submit",
		Short:   "Submit a signed order",
		Long:    "Submit a signed order to the resolver network.\n\nThe body echoes the `order` fields from `/order` (`signed_order`,\n`extension`, `quote_id`, optionally `order_hash`) plus the owner's\nsignature over `order.safe_message_eip712`. The maker on the order\nstruct is the Tokenized Assets Account, not the owner's wallet —\npass `signed_order` back unchanged.\n\nReturns the order hash and a server-side ISO 8601 timestamp.\nSubsequent calls to `GET /order/{order_hash}` track the lifecycle\n(`pending` → `filled` / `expired` / `cancelled`).",
		Example: "  compass tokenized-assets tokenized-assets-order-submit --signed-order '{\"key\":\"<value>\"}' --signature <value> --extension m2a --quote-id <id>",
		RunE:    runTokenizedAssetsOrderSubmitCmd,
		Aliases: []string{"taos"},
	}
	flagutil.RegisterFlags(cmd, tokenizedAssetsOrderSubmitCmdMeta)
	if err := flagutil.ValidateMeta[components.TokenizedAssetsSubmitOrderRequest](tokenizedAssetsOrderSubmitCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for tokenized-assets-order-submit: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runTokenizedAssetsOrderSubmitCmd executes the tokenized-assets-order-submit command.
func runTokenizedAssetsOrderSubmitCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, tokenizedAssetsOrderSubmitCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, tokenizedAssetsOrderSubmitCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.TokenizedAssetsSubmitOrderRequest](cmd, tokenizedAssetsOrderSubmitCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.TokenizedAssets.TokenizedAssetsOrderSubmit(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
