// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
	"github.com/CompassLabs/cli/internal/sdk/types"
)

type CompassAPIBackendV2ModelsGasSponsorshipPermit2TypedDataEip712Domain struct {
	// Must be 'Permit2'
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	name *string `const:"Permit2" json:"name,omitzero"`
	// EVM chain ID
	ChainID int64 `json:"chainId"`
	// Permit2 contract address
	VerifyingContract string `json:"verifyingContract"`
}

func (c CompassAPIBackendV2ModelsGasSponsorshipPermit2TypedDataEip712Domain) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CompassAPIBackendV2ModelsGasSponsorshipPermit2TypedDataEip712Domain) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CompassAPIBackendV2ModelsGasSponsorshipPermit2TypedDataEip712Domain) GetName() *string {
	return types.Pointer("Permit2")
}

func (c *CompassAPIBackendV2ModelsGasSponsorshipPermit2TypedDataEip712Domain) GetChainID() int64 {
	if c == nil {
		return 0
	}
	return c.ChainID
}

func (c *CompassAPIBackendV2ModelsGasSponsorshipPermit2TypedDataEip712Domain) GetVerifyingContract() string {
	if c == nil {
		return ""
	}
	return c.VerifyingContract
}

// #region class-body-compassapibackendv2modelsgassponsorshippermit2typeddataeip712domain
// #endregion class-body-compassapibackendv2modelsgassponsorshippermit2typeddataeip712domain
