// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

// CompassAPIBackendV2ModelsTokenizedAssetsMarketMarketChain - Chain on which the contract is deployed.
type CompassAPIBackendV2ModelsTokenizedAssetsMarketMarketChain string

const (
	CompassAPIBackendV2ModelsTokenizedAssetsMarketMarketChainEthereum CompassAPIBackendV2ModelsTokenizedAssetsMarketMarketChain = "ethereum"
)

func (e CompassAPIBackendV2ModelsTokenizedAssetsMarketMarketChain) ToPointer() *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarketChain {
	return &e
}
func (e *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarketChain) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ethereum":
		*e = CompassAPIBackendV2ModelsTokenizedAssetsMarketMarketChain(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CompassAPIBackendV2ModelsTokenizedAssetsMarketMarketChain: %v", v)
	}
}

// CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket - Compact market entry returned in list responses.
type CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket struct {
	// On-chain token symbol (e.g. 'TSLAon').
	Symbol string `json:"symbol"`
	// Underlying equity ticker (e.g. 'TSLA').
	UnderlyingTicker string `json:"underlying_ticker"`
	// Underlying equity full name (e.g. 'Tesla, Inc. Common Stock').
	Name string `json:"name"`
	// Chain on which the contract is deployed.
	Chain *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarketChain `json:"chain,omitzero"`
	// Ethereum mainnet ERC-20 address for this token.
	ContractAddress string `json:"contract_address"`
	// ERC-20 decimals for this token.
	Decimals int64 `json:"decimals"`
	// Latest price in USD as a decimal string.
	CurrentPriceUsd string `json:"current_price_usd"`
	// Absolute USD price change vs 24h ago (decimal string).
	Change24hUsd optionalnullable.OptionalNullable[string] `json:"change_24h_usd,omitzero"`
	// Percent price change vs 24h ago (decimal string).
	Change24hPct optionalnullable.OptionalNullable[string] `json:"change_24h_pct,omitzero"`
	// Sector / industry tags from the issuer (e.g. ['Technology']).
	Sectors []string `json:"sectors,omitzero"`
	// Regional market exposure tags (e.g. ['US']).
	RegionExposure []string `json:"region_exposure,omitzero"`
}

func (c CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket) GetSymbol() string {
	if c == nil {
		return ""
	}
	return c.Symbol
}

func (c *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket) GetUnderlyingTicker() string {
	if c == nil {
		return ""
	}
	return c.UnderlyingTicker
}

func (c *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket) GetChain() *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarketChain {
	if c == nil {
		return nil
	}
	return c.Chain
}

func (c *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket) GetContractAddress() string {
	if c == nil {
		return ""
	}
	return c.ContractAddress
}

func (c *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket) GetDecimals() int64 {
	if c == nil {
		return 0
	}
	return c.Decimals
}

func (c *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket) GetCurrentPriceUsd() string {
	if c == nil {
		return ""
	}
	return c.CurrentPriceUsd
}

func (c *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket) GetChange24hUsd() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Change24hUsd
}

func (c *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket) GetChange24hPct() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Change24hPct
}

func (c *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket) GetSectors() []string {
	if c == nil {
		return nil
	}
	return c.Sectors
}

func (c *CompassAPIBackendV2ModelsTokenizedAssetsMarketMarket) GetRegionExposure() []string {
	if c == nil {
		return nil
	}
	return c.RegionExposure
}

// #region class-body-compassapibackendv2modelstokenizedassetsmarketmarket
// #endregion class-body-compassapibackendv2modelstokenizedassetsmarketmarket
