// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type CreateAccountRequestChain string

const (
	CreateAccountRequestChainArbitrum CreateAccountRequestChain = "arbitrum"
	CreateAccountRequestChainBase     CreateAccountRequestChain = "base"
	CreateAccountRequestChainEthereum CreateAccountRequestChain = "ethereum"
	CreateAccountRequestChainTempo    CreateAccountRequestChain = "tempo"
)

func (e CreateAccountRequestChain) ToPointer() *CreateAccountRequestChain {
	return &e
}
func (e *CreateAccountRequestChain) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "arbitrum":
		fallthrough
	case "base":
		fallthrough
	case "ethereum":
		fallthrough
	case "tempo":
		*e = CreateAccountRequestChain(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateAccountRequestChain: %v", v)
	}
}

// CreateAccountRequest - Request to create a compass account.
type CreateAccountRequest struct {
	Chain CreateAccountRequestChain `json:"chain"`
	// The address of the transaction sender.
	Sender string `json:"sender"`
	// Determines whether to estimate gas costs for transactions, also verifying that the transaction can be successfully executed.
	EstimateGas *bool `json:"estimate_gas,omitzero"`
	// The address that will own and control the compass account
	Owner string `json:"owner"`
}

func (c *CreateAccountRequest) GetChain() CreateAccountRequestChain {
	if c == nil {
		return CreateAccountRequestChain("")
	}
	return c.Chain
}

func (c *CreateAccountRequest) GetSender() string {
	if c == nil {
		return ""
	}
	return c.Sender
}

func (c *CreateAccountRequest) GetEstimateGas() *bool {
	if c == nil {
		return nil
	}
	return c.EstimateGas
}

func (c *CreateAccountRequest) GetOwner() string {
	if c == nil {
		return ""
	}
	return c.Owner
}
