// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CreditBundleRequest - Request to execute multiple credit actions in a single atomic transaction.
type CreditBundleRequest struct {
	// The owner's wallet address that controls the Credit Account.
	Owner string `json:"owner"`
	// The chain to use.
	Chain Chain `json:"chain"`
	// List of actions to bundle. Actions are executed in order.
	Actions []CreditUserOperation `json:"actions"`
	// If true, returns EIP-712 typed data for gas-sponsored execution.
	GasSponsorship *bool `json:"gas_sponsorship,omitzero"`
}

func (c *CreditBundleRequest) GetOwner() string {
	if c == nil {
		return ""
	}
	return c.Owner
}

func (c *CreditBundleRequest) GetChain() Chain {
	if c == nil {
		return Chain("")
	}
	return c.Chain
}

func (c *CreditBundleRequest) GetActions() []CreditUserOperation {
	if c == nil {
		return []CreditUserOperation{}
	}
	return c.Actions
}

func (c *CreditBundleRequest) GetGasSponsorship() *bool {
	if c == nil {
		return nil
	}
	return c.GasSponsorship
}
