// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

// CreditBalancesResponse - Response containing credit account balances and transfer history.
type CreditBalancesResponse struct {
	// The derived credit account address.
	CreditAccountAddress string `json:"credit_account_address"`
	// Token balances keyed by token symbol.
	Balances map[string]CompassAPIBackendV2ModelsBalancesTokenBalance `json:"balances,omitzero"`
	// Total USD value of all balances (sum of available values).
	TotalUsdValue optionalnullable.OptionalNullable[string] `json:"total_usd_value,omitzero"`
}

func (c CreditBalancesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditBalancesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreditBalancesResponse) GetCreditAccountAddress() string {
	if c == nil {
		return ""
	}
	return c.CreditAccountAddress
}

func (c *CreditBalancesResponse) GetBalances() map[string]CompassAPIBackendV2ModelsBalancesTokenBalance {
	if c == nil {
		return nil
	}
	return c.Balances
}

func (c *CreditBalancesResponse) GetTotalUsdValue() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.TotalUsdValue
}
