// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type CreditUserOperationBodyType string

const (
	CreditUserOperationBodyTypeCreditBorrow            CreditUserOperationBodyType = "CREDIT_BORROW"
	CreditUserOperationBodyTypeCreditEnableCollateral  CreditUserOperationBodyType = "CREDIT_ENABLE_COLLATERAL"
	CreditUserOperationBodyTypeCreditRepay             CreditUserOperationBodyType = "CREDIT_REPAY"
	CreditUserOperationBodyTypeCreditSupply            CreditUserOperationBodyType = "CREDIT_SUPPLY"
	CreditUserOperationBodyTypeCreditTransferToAddress CreditUserOperationBodyType = "CREDIT_TRANSFER_TO_ADDRESS"
	CreditUserOperationBodyTypeCreditWithdraw          CreditUserOperationBodyType = "CREDIT_WITHDRAW"
	CreditUserOperationBodyTypeV2Swap                  CreditUserOperationBodyType = "V2_SWAP"
	CreditUserOperationBodyTypeV2TransferFromEoa       CreditUserOperationBodyType = "V2_TRANSFER_FROM_EOA"
	CreditUserOperationBodyTypeV2TransferToEoa         CreditUserOperationBodyType = "V2_TRANSFER_TO_EOA"
)

type CreditUserOperationBody struct {
	EarnSwapParams                *EarnSwapParams                `queryParam:"inline" union:"member"`
	EarnTransferFromEOAParams     *EarnTransferFromEOAParams     `queryParam:"inline" union:"member"`
	EarnTransferToEOAParams       *EarnTransferToEOAParams       `queryParam:"inline" union:"member"`
	CreditSupplyParams            *CreditSupplyParams            `queryParam:"inline" union:"member"`
	CreditWithdrawParams          *CreditWithdrawParams          `queryParam:"inline" union:"member"`
	CreditBorrowParams            *CreditBorrowParams            `queryParam:"inline" union:"member"`
	CreditRepayParams             *CreditRepayParams             `queryParam:"inline" union:"member"`
	CreditEnableCollateralParams  *CreditEnableCollateralParams  `queryParam:"inline" union:"member"`
	CreditTransferToAddressParams *CreditTransferToAddressParams `queryParam:"inline" union:"member"`

	Type CreditUserOperationBodyType
}

func CreateCreditUserOperationBodyCreditBorrow(creditBorrow CreditBorrowParams) CreditUserOperationBody {
	typ := CreditUserOperationBodyTypeCreditBorrow

	return CreditUserOperationBody{
		CreditBorrowParams: &creditBorrow,
		Type:               typ,
	}
}

func CreateCreditUserOperationBodyCreditEnableCollateral(creditEnableCollateral CreditEnableCollateralParams) CreditUserOperationBody {
	typ := CreditUserOperationBodyTypeCreditEnableCollateral

	return CreditUserOperationBody{
		CreditEnableCollateralParams: &creditEnableCollateral,
		Type:                         typ,
	}
}

func CreateCreditUserOperationBodyCreditRepay(creditRepay CreditRepayParams) CreditUserOperationBody {
	typ := CreditUserOperationBodyTypeCreditRepay

	return CreditUserOperationBody{
		CreditRepayParams: &creditRepay,
		Type:              typ,
	}
}

func CreateCreditUserOperationBodyCreditSupply(creditSupply CreditSupplyParams) CreditUserOperationBody {
	typ := CreditUserOperationBodyTypeCreditSupply

	return CreditUserOperationBody{
		CreditSupplyParams: &creditSupply,
		Type:               typ,
	}
}

func CreateCreditUserOperationBodyCreditTransferToAddress(creditTransferToAddress CreditTransferToAddressParams) CreditUserOperationBody {
	typ := CreditUserOperationBodyTypeCreditTransferToAddress

	return CreditUserOperationBody{
		CreditTransferToAddressParams: &creditTransferToAddress,
		Type:                          typ,
	}
}

func CreateCreditUserOperationBodyCreditWithdraw(creditWithdraw CreditWithdrawParams) CreditUserOperationBody {
	typ := CreditUserOperationBodyTypeCreditWithdraw

	return CreditUserOperationBody{
		CreditWithdrawParams: &creditWithdraw,
		Type:                 typ,
	}
}

func CreateCreditUserOperationBodyV2Swap(v2Swap EarnSwapParams) CreditUserOperationBody {
	typ := CreditUserOperationBodyTypeV2Swap

	return CreditUserOperationBody{
		EarnSwapParams: &v2Swap,
		Type:           typ,
	}
}

func CreateCreditUserOperationBodyV2TransferFromEoa(v2TransferFromEoa EarnTransferFromEOAParams) CreditUserOperationBody {
	typ := CreditUserOperationBodyTypeV2TransferFromEoa

	return CreditUserOperationBody{
		EarnTransferFromEOAParams: &v2TransferFromEoa,
		Type:                      typ,
	}
}

func CreateCreditUserOperationBodyV2TransferToEoa(v2TransferToEoa EarnTransferToEOAParams) CreditUserOperationBody {
	typ := CreditUserOperationBodyTypeV2TransferToEoa

	return CreditUserOperationBody{
		EarnTransferToEOAParams: &v2TransferToEoa,
		Type:                    typ,
	}
}

func (u *CreditUserOperationBody) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		ActionType string `json:"action_type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.ActionType {
	case "CREDIT_BORROW":
		creditBorrowParams := new(CreditBorrowParams)
		if err := utils.UnmarshalJSON(data, &creditBorrowParams, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == CREDIT_BORROW) type CreditBorrowParams within CreditUserOperationBody: %w", string(data), err)
		}

		u.CreditBorrowParams = creditBorrowParams
		u.Type = CreditUserOperationBodyTypeCreditBorrow
		return nil
	case "CREDIT_ENABLE_COLLATERAL":
		creditEnableCollateralParams := new(CreditEnableCollateralParams)
		if err := utils.UnmarshalJSON(data, &creditEnableCollateralParams, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == CREDIT_ENABLE_COLLATERAL) type CreditEnableCollateralParams within CreditUserOperationBody: %w", string(data), err)
		}

		u.CreditEnableCollateralParams = creditEnableCollateralParams
		u.Type = CreditUserOperationBodyTypeCreditEnableCollateral
		return nil
	case "CREDIT_REPAY":
		creditRepayParams := new(CreditRepayParams)
		if err := utils.UnmarshalJSON(data, &creditRepayParams, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == CREDIT_REPAY) type CreditRepayParams within CreditUserOperationBody: %w", string(data), err)
		}

		u.CreditRepayParams = creditRepayParams
		u.Type = CreditUserOperationBodyTypeCreditRepay
		return nil
	case "CREDIT_SUPPLY":
		creditSupplyParams := new(CreditSupplyParams)
		if err := utils.UnmarshalJSON(data, &creditSupplyParams, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == CREDIT_SUPPLY) type CreditSupplyParams within CreditUserOperationBody: %w", string(data), err)
		}

		u.CreditSupplyParams = creditSupplyParams
		u.Type = CreditUserOperationBodyTypeCreditSupply
		return nil
	case "CREDIT_TRANSFER_TO_ADDRESS":
		creditTransferToAddressParams := new(CreditTransferToAddressParams)
		if err := utils.UnmarshalJSON(data, &creditTransferToAddressParams, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == CREDIT_TRANSFER_TO_ADDRESS) type CreditTransferToAddressParams within CreditUserOperationBody: %w", string(data), err)
		}

		u.CreditTransferToAddressParams = creditTransferToAddressParams
		u.Type = CreditUserOperationBodyTypeCreditTransferToAddress
		return nil
	case "CREDIT_WITHDRAW":
		creditWithdrawParams := new(CreditWithdrawParams)
		if err := utils.UnmarshalJSON(data, &creditWithdrawParams, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == CREDIT_WITHDRAW) type CreditWithdrawParams within CreditUserOperationBody: %w", string(data), err)
		}

		u.CreditWithdrawParams = creditWithdrawParams
		u.Type = CreditUserOperationBodyTypeCreditWithdraw
		return nil
	case "V2_SWAP":
		earnSwapParams := new(EarnSwapParams)
		if err := utils.UnmarshalJSON(data, &earnSwapParams, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == V2_SWAP) type EarnSwapParams within CreditUserOperationBody: %w", string(data), err)
		}

		u.EarnSwapParams = earnSwapParams
		u.Type = CreditUserOperationBodyTypeV2Swap
		return nil
	case "V2_TRANSFER_FROM_EOA":
		earnTransferFromEOAParams := new(EarnTransferFromEOAParams)
		if err := utils.UnmarshalJSON(data, &earnTransferFromEOAParams, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == V2_TRANSFER_FROM_EOA) type EarnTransferFromEOAParams within CreditUserOperationBody: %w", string(data), err)
		}

		u.EarnTransferFromEOAParams = earnTransferFromEOAParams
		u.Type = CreditUserOperationBodyTypeV2TransferFromEoa
		return nil
	case "V2_TRANSFER_TO_EOA":
		earnTransferToEOAParams := new(EarnTransferToEOAParams)
		if err := utils.UnmarshalJSON(data, &earnTransferToEOAParams, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ActionType == V2_TRANSFER_TO_EOA) type EarnTransferToEOAParams within CreditUserOperationBody: %w", string(data), err)
		}

		u.EarnTransferToEOAParams = earnTransferToEOAParams
		u.Type = CreditUserOperationBodyTypeV2TransferToEoa
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreditUserOperationBody", string(data))
}

func (u CreditUserOperationBody) MarshalJSON() ([]byte, error) {
	if u.EarnSwapParams != nil {
		return utils.MarshalJSON(u.EarnSwapParams, "", true)
	}

	if u.EarnTransferFromEOAParams != nil {
		return utils.MarshalJSON(u.EarnTransferFromEOAParams, "", true)
	}

	if u.EarnTransferToEOAParams != nil {
		return utils.MarshalJSON(u.EarnTransferToEOAParams, "", true)
	}

	if u.CreditSupplyParams != nil {
		return utils.MarshalJSON(u.CreditSupplyParams, "", true)
	}

	if u.CreditWithdrawParams != nil {
		return utils.MarshalJSON(u.CreditWithdrawParams, "", true)
	}

	if u.CreditBorrowParams != nil {
		return utils.MarshalJSON(u.CreditBorrowParams, "", true)
	}

	if u.CreditRepayParams != nil {
		return utils.MarshalJSON(u.CreditRepayParams, "", true)
	}

	if u.CreditEnableCollateralParams != nil {
		return utils.MarshalJSON(u.CreditEnableCollateralParams, "", true)
	}

	if u.CreditTransferToAddressParams != nil {
		return utils.MarshalJSON(u.CreditTransferToAddressParams, "", true)
	}

	return nil, errors.New("could not marshal union type CreditUserOperationBody: all fields are null")
}

// CreditUserOperation - A single operation in a credit bundle.
type CreditUserOperation struct {
	Body CreditUserOperationBody `json:"body"`
}

func (c *CreditUserOperation) GetBody() CreditUserOperationBody {
	if c == nil {
		return CreditUserOperationBody{}
	}
	return c.Body
}

func (c *CreditUserOperation) GetBodyCreditBorrow() *CreditBorrowParams {
	return c.GetBody().CreditBorrowParams
}

func (c *CreditUserOperation) GetBodyCreditEnableCollateral() *CreditEnableCollateralParams {
	return c.GetBody().CreditEnableCollateralParams
}

func (c *CreditUserOperation) GetBodyCreditRepay() *CreditRepayParams {
	return c.GetBody().CreditRepayParams
}

func (c *CreditUserOperation) GetBodyCreditSupply() *CreditSupplyParams {
	return c.GetBody().CreditSupplyParams
}

func (c *CreditUserOperation) GetBodyCreditTransferToAddress() *CreditTransferToAddressParams {
	return c.GetBody().CreditTransferToAddressParams
}

func (c *CreditUserOperation) GetBodyCreditWithdraw() *CreditWithdrawParams {
	return c.GetBody().CreditWithdrawParams
}

func (c *CreditUserOperation) GetBodyV2Swap() *EarnSwapParams {
	return c.GetBody().EarnSwapParams
}

func (c *CreditUserOperation) GetBodyV2TransferFromEoa() *EarnTransferFromEOAParams {
	return c.GetBody().EarnTransferFromEOAParams
}

func (c *CreditUserOperation) GetBodyV2TransferToEoa() *EarnTransferToEOAParams {
	return c.GetBody().EarnTransferToEOAParams
}
