// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CreditProtocol - Which lending protocol a credit action targets.
//
// “AAVE“ is the default so existing callers (which never send a “protocol“
// field) keep hitting the unchanged Aave code path; markets are named by token
// symbol. “MORPHO“ identifies Morpho Blue lending markets by their bytes32
// “market_id“. “EULER“ identifies Euler V2 markets by their EVK
// “collateral_vault“ + “borrow_vault“ addresses and supports isolated
// per-sub-account positions (“sub_account_id“).
//
// Deployment is per chain, so a valid protocol can still 422 on a given chain:
// AAVE on Ethereum, Base, Arbitrum, BSC and HyperEVM (where it is Hyperlend, the
// chain's Aave V3 deployment); MORPHO on Ethereum, Base, Arbitrum and HyperEVM
// (where it is Felix); EULER on Ethereum, Base, Arbitrum and BSC.
//
// All three support “/v2/credit/loop“, “/v2/credit/unloop“ and
// “/v2/credit/looped_positions“. The one gap is “/v2/credit/rebalance“,
// which rejects EULER with a 422.
type CreditProtocol string

const (
	CreditProtocolAave   CreditProtocol = "AAVE"
	CreditProtocolEuler  CreditProtocol = "EULER"
	CreditProtocolMorpho CreditProtocol = "MORPHO"
)

func (e CreditProtocol) ToPointer() *CreditProtocol {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CreditProtocol) IsExact() bool {
	if e != nil {
		switch *e {
		case "AAVE", "EULER", "MORPHO":
			return true
		}
	}
	return false
}
