// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type CreditBorrowRequestAmountInType string

const (
	CreditBorrowRequestAmountInTypeNumber CreditBorrowRequestAmountInType = "number"
	CreditBorrowRequestAmountInTypeStr    CreditBorrowRequestAmountInType = "str"
)

// CreditBorrowRequestAmountIn - Amount of token_in to use (in token units, not wei). Omit together with token_in and collateral_token for borrow-only mode.
type CreditBorrowRequestAmountIn struct {
	Number *float64 `queryParam:"inline" union:"member"`
	Str    *string  `queryParam:"inline" union:"member"`

	Type CreditBorrowRequestAmountInType
}

func CreateCreditBorrowRequestAmountInNumber(number float64) CreditBorrowRequestAmountIn {
	typ := CreditBorrowRequestAmountInTypeNumber

	return CreditBorrowRequestAmountIn{
		Number: &number,
		Type:   typ,
	}
}

func CreateCreditBorrowRequestAmountInStr(str string) CreditBorrowRequestAmountIn {
	typ := CreditBorrowRequestAmountInTypeStr

	return CreditBorrowRequestAmountIn{
		Str:  &str,
		Type: typ,
	}
}

func (u *CreditBorrowRequestAmountIn) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreditBorrowRequestAmountInTypeNumber,
			Value: &number,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreditBorrowRequestAmountInTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreditBorrowRequestAmountIn", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreditBorrowRequestAmountIn", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(CreditBorrowRequestAmountInType)
	switch best.Type {
	case CreditBorrowRequestAmountInTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case CreditBorrowRequestAmountInTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreditBorrowRequestAmountIn", string(data))
}

func (u CreditBorrowRequestAmountIn) MarshalJSON() ([]byte, error) {
	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type CreditBorrowRequestAmountIn: all fields are null")
}

type BorrowAmountType string

const (
	BorrowAmountTypeNumber BorrowAmountType = "number"
	BorrowAmountTypeStr    BorrowAmountType = "str"
)

// BorrowAmount - Amount to borrow (in token units, not wei).
type BorrowAmount struct {
	Number *float64 `queryParam:"inline" union:"member"`
	Str    *string  `queryParam:"inline" union:"member"`

	Type BorrowAmountType
}

func CreateBorrowAmountNumber(number float64) BorrowAmount {
	typ := BorrowAmountTypeNumber

	return BorrowAmount{
		Number: &number,
		Type:   typ,
	}
}

func CreateBorrowAmountStr(str string) BorrowAmount {
	typ := BorrowAmountTypeStr

	return BorrowAmount{
		Str:  &str,
		Type: typ,
	}
}

func (u *BorrowAmount) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  BorrowAmountTypeNumber,
			Value: &number,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  BorrowAmountTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for BorrowAmount", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for BorrowAmount", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(BorrowAmountType)
	switch best.Type {
	case BorrowAmountTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case BorrowAmountTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for BorrowAmount", string(data))
}

func (u BorrowAmount) MarshalJSON() ([]byte, error) {
	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type BorrowAmount: all fields are null")
}

type CreditBorrowRequestSlippageType string

const (
	CreditBorrowRequestSlippageTypeNumber CreditBorrowRequestSlippageType = "number"
	CreditBorrowRequestSlippageTypeStr    CreditBorrowRequestSlippageType = "str"
)

// CreditBorrowRequestSlippage - Maximum slippage tolerance as a percentage (e.g., 0.5 = 0.5%). Only used when a swap is needed.
type CreditBorrowRequestSlippage struct {
	Number *float64 `queryParam:"inline" union:"member"`
	Str    *string  `queryParam:"inline" union:"member"`

	Type CreditBorrowRequestSlippageType
}

func CreateCreditBorrowRequestSlippageNumber(number float64) CreditBorrowRequestSlippage {
	typ := CreditBorrowRequestSlippageTypeNumber

	return CreditBorrowRequestSlippage{
		Number: &number,
		Type:   typ,
	}
}

func CreateCreditBorrowRequestSlippageStr(str string) CreditBorrowRequestSlippage {
	typ := CreditBorrowRequestSlippageTypeStr

	return CreditBorrowRequestSlippage{
		Str:  &str,
		Type: typ,
	}
}

func (u *CreditBorrowRequestSlippage) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreditBorrowRequestSlippageTypeNumber,
			Value: &number,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreditBorrowRequestSlippageTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreditBorrowRequestSlippage", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreditBorrowRequestSlippage", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(CreditBorrowRequestSlippageType)
	switch best.Type {
	case CreditBorrowRequestSlippageTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case CreditBorrowRequestSlippageTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreditBorrowRequestSlippage", string(data))
}

func (u CreditBorrowRequestSlippage) MarshalJSON() ([]byte, error) {
	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type CreditBorrowRequestSlippage: all fields are null")
}

type CreditBorrowRequest struct {
	// The address that owns the Credit Account.
	Owner string `json:"owner"`
	// The chain to use.
	Chain Chain `json:"chain"`
	// Token currently held in the Credit Account to use as input. If the same as collateral_token, no swap is performed. Omit together with amount_in and collateral_token to borrow against existing collateral.
	TokenIn optionalnullable.OptionalNullable[string] `json:"token_in,omitzero"`
	// Amount of token_in to use (in token units, not wei). Omit together with token_in and collateral_token for borrow-only mode.
	AmountIn optionalnullable.OptionalNullable[CreditBorrowRequestAmountIn] `json:"amount_in,omitzero"`
	// Aave reserve token to supply as collateral. Omit together with token_in and amount_in for borrow-only mode.
	CollateralToken optionalnullable.OptionalNullable[string] `json:"collateral_token,omitzero"`
	// Asset to borrow from Aave.
	BorrowToken string `json:"borrow_token"`
	// Amount to borrow (in token units, not wei).
	BorrowAmount BorrowAmount `json:"borrow_amount"`
	// On AAVE there are 2 different interest modes.
	//
	// A stable (but typically higher rate), or a variable rate.
	InterestRateMode *InterestRateMode `json:"interest_rate_mode,omitzero"`
	// Maximum slippage tolerance as a percentage (e.g., 0.5 = 0.5%). Only used when a swap is needed.
	Slippage *CreditBorrowRequestSlippage `json:"slippage,omitzero"`
	// If true, returns EIP-712 signature data instead of an unsigned transaction.
	GasSponsorship *bool `json:"gas_sponsorship,omitzero"`
	// Optional fee configuration. If provided, a fee will be deducted from the borrowed amount and sent to the specified recipient address.
	Fee optionalnullable.OptionalNullable[CreditFee] `json:"fee,omitzero"`
	// The EOA owner's signature of the Permit2 PermitTransferFrom typed data. When provided, the borrow bundle will first pull token_in from the owner's EOA into the Credit Account via Permit2. Obtain by calling /v2/credit/transfer and signing the returned EIP-712 data.
	Permit2Signature optionalnullable.OptionalNullable[string] `json:"permit2_signature,omitzero"`
	// The nonce used in the Permit2 signature (from the signed typed data).
	Permit2Nonce optionalnullable.OptionalNullable[int64] `json:"permit2_nonce,omitzero"`
	// The deadline timestamp used in the Permit2 signature (from the signed typed data).
	Permit2Deadline optionalnullable.OptionalNullable[int64] `json:"permit2_deadline,omitzero"`
}

func (c CreditBorrowRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditBorrowRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreditBorrowRequest) GetOwner() string {
	if c == nil {
		return ""
	}
	return c.Owner
}

func (c *CreditBorrowRequest) GetChain() Chain {
	if c == nil {
		return Chain("")
	}
	return c.Chain
}

func (c *CreditBorrowRequest) GetTokenIn() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.TokenIn
}

func (c *CreditBorrowRequest) GetAmountIn() optionalnullable.OptionalNullable[CreditBorrowRequestAmountIn] {
	if c == nil {
		return nil
	}
	return c.AmountIn
}

func (c *CreditBorrowRequest) GetCollateralToken() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.CollateralToken
}

func (c *CreditBorrowRequest) GetBorrowToken() string {
	if c == nil {
		return ""
	}
	return c.BorrowToken
}

func (c *CreditBorrowRequest) GetBorrowAmount() BorrowAmount {
	if c == nil {
		return BorrowAmount{}
	}
	return c.BorrowAmount
}

func (c *CreditBorrowRequest) GetInterestRateMode() *InterestRateMode {
	if c == nil {
		return nil
	}
	return c.InterestRateMode
}

func (c *CreditBorrowRequest) GetSlippage() *CreditBorrowRequestSlippage {
	if c == nil {
		return nil
	}
	return c.Slippage
}

func (c *CreditBorrowRequest) GetGasSponsorship() *bool {
	if c == nil {
		return nil
	}
	return c.GasSponsorship
}

func (c *CreditBorrowRequest) GetFee() optionalnullable.OptionalNullable[CreditFee] {
	if c == nil {
		return nil
	}
	return c.Fee
}

func (c *CreditBorrowRequest) GetPermit2Signature() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Permit2Signature
}

func (c *CreditBorrowRequest) GetPermit2Nonce() optionalnullable.OptionalNullable[int64] {
	if c == nil {
		return nil
	}
	return c.Permit2Nonce
}

func (c *CreditBorrowRequest) GetPermit2Deadline() optionalnullable.OptionalNullable[int64] {
	if c == nil {
		return nil
	}
	return c.Permit2Deadline
}
