// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
	"github.com/CompassLabs/cli/internal/sdk/types"
)

// CreditEnableCollateralParams - Enable a reserve asset as collateral in Aave via Credit Account.
//
// Required after receiving aTokens via direct ERC-20 transfer (not via Pool.supply()),
// since Aave V3 does not auto-enable collateral for transferred aTokens.
type CreditEnableCollateralParams struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	actionType *string `const:"CREDIT_ENABLE_COLLATERAL" json:"action_type,omitzero"`
	// The underlying reserve token to enable as collateral (e.g. USDC, not aUSDC).
	Token string `json:"token"`
	// Which lending protocol a credit action targets.
	//
	// ``AAVE`` is the default so existing callers (which never send a ``protocol``
	// field) keep hitting the unchanged Aave code path. ``EULER`` opts in to the
	// Euler V2 path, where the market is identified by EVK vault address(es).
	Protocol *CreditProtocol `json:"protocol,omitzero"`
	// Euler only: the EVK collateral vault to enable. Required when protocol=EULER.
	CollateralVault optionalnullable.OptionalNullable[string] `json:"collateral_vault,omitzero"`
}

func (c CreditEnableCollateralParams) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditEnableCollateralParams) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreditEnableCollateralParams) GetActionType() *string {
	return types.Pointer("CREDIT_ENABLE_COLLATERAL")
}

func (c *CreditEnableCollateralParams) GetToken() string {
	if c == nil {
		return ""
	}
	return c.Token
}

func (c *CreditEnableCollateralParams) GetProtocol() *CreditProtocol {
	if c == nil {
		return nil
	}
	return c.Protocol
}

func (c *CreditEnableCollateralParams) GetCollateralVault() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.CollateralVault
}
