// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// EventType - Type of credit event.
type EventType string

const (
	EventTypeSupply      EventType = "supply"
	EventTypeWithdraw    EventType = "withdraw"
	EventTypeBorrow      EventType = "borrow"
	EventTypeRepay       EventType = "repay"
	EventTypeLiquidation EventType = "liquidation"
	EventTypeTransferIn  EventType = "transfer_in"
	EventTypeTransferOut EventType = "transfer_out"
)

func (e EventType) ToPointer() *EventType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EventType) IsExact() bool {
	if e != nil {
		switch *e {
		case "supply", "withdraw", "borrow", "repay", "liquidation", "transfer_in", "transfer_out":
			return true
		}
	}
	return false
}

// CreditEvent - A single historical event in a credit position.
type CreditEvent struct {
	// Type of credit event.
	EventType EventType `json:"event_type"`
	// Block number when the event occurred
	BlockNumber int64 `json:"block_number"`
	// Timestamp when the event occurred
	BlockTimestamp time.Time `json:"block_timestamp"`
	// Transaction hash of the event
	TransactionHash string `json:"transaction_hash"`
	// Amount involved in the event
	Amount string `json:"amount"`
	// Symbol of the token
	Symbol string `json:"symbol"`
}

func (c CreditEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreditEvent) GetEventType() EventType {
	if c == nil {
		return EventType("")
	}
	return c.EventType
}

func (c *CreditEvent) GetBlockNumber() int64 {
	if c == nil {
		return 0
	}
	return c.BlockNumber
}

func (c *CreditEvent) GetBlockTimestamp() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.BlockTimestamp
}

func (c *CreditEvent) GetTransactionHash() string {
	if c == nil {
		return ""
	}
	return c.TransactionHash
}

func (c *CreditEvent) GetAmount() string {
	if c == nil {
		return ""
	}
	return c.Amount
}

func (c *CreditEvent) GetSymbol() string {
	if c == nil {
		return ""
	}
	return c.Symbol
}
