// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// Generated under the AGPL-3.0-only license.
// SPDX-License-Identifier: AGPL-3.0-only

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

// DebtPosition - A per-reserve debt position.
type DebtPosition struct {
	// Address of the borrow token.
	Token string `json:"token"`
	// Symbol of the borrow token (e.g. WETH).
	Symbol string `json:"symbol"`
	// Which lending protocol a credit action targets.
	//
	// ``AAVE`` is the default so existing callers (which never send a ``protocol``
	// field) keep hitting the unchanged Aave code path; markets are named by token
	// symbol. ``MORPHO`` identifies Morpho Blue lending markets by their bytes32
	// ``market_id``. ``EULER`` identifies Euler V2 markets by their EVK
	// ``collateral_vault`` + ``borrow_vault`` addresses and supports isolated
	// per-sub-account positions (``sub_account_id``).
	//
	// Deployment is per chain, so a valid protocol can still 422 on a given chain:
	// AAVE on Ethereum, Base, Arbitrum, BSC and HyperEVM (where it is Hyperlend, the
	// chain's Aave V3 deployment); MORPHO on Ethereum, Base, Arbitrum and HyperEVM
	// (where it is Felix); EULER on Ethereum, Base, Arbitrum and BSC.
	//
	// All three support ``/v2/credit/loop`` and ``/v2/credit/unloop``. EULER does
	// NOT: ``/v2/credit/rebalance`` rejects it with a 422, and
	// ``/v2/credit/looped_positions`` covers only AAVE and MORPHO — an Euler loop is
	// silently absent there rather than an error, so read it from
	// ``/v2/credit/positions`` instead. (EULER still appears in the
	// ``looped_positions`` response enum because this enum is shared; it is never
	// emitted.)
	Protocol *CreditProtocol `json:"protocol,omitzero"`
	// Euler only: the EVK borrow vault this debt is owed to.
	Vault optionalnullable.OptionalNullable[string] `json:"vault,omitzero"`
	// Euler only: the EVC sub-account (0–255) this debt belongs to. Each sub-account is an independent Euler position with its own health. Null for Aave/Morpho.
	SubAccountID optionalnullable.OptionalNullable[int64] `json:"sub_account_id,omitzero"`
	// Morpho only: the bytes32 id of the isolated market this debt is owed to.
	MarketID optionalnullable.OptionalNullable[string] `json:"market_id,omitzero"`
	// Morpho only: this market's health factor (markets are isolated, so health is per market — below 1 the position is liquidatable). Null for other protocols and when the oracle read fails.
	HealthFactor optionalnullable.OptionalNullable[string] `json:"health_factor,omitzero"`
	// Current on-chain debt balance (the vault's underlying asset for Euler).
	AmountBorrowed *string `json:"amount_borrowed"`
	// Debt value in USD.
	UsdValue optionalnullable.OptionalNullable[string] `json:"usd_value,omitzero"`
	// Current borrow APY in percentage (e.g. 4.5 means 4.5%).
	BorrowApy optionalnullable.OptionalNullable[string] `json:"borrow_apy,omitzero"`
	// Total amount borrowed across all borrow events.
	TotalBorrowed optionalnullable.OptionalNullable[string] `json:"total_borrowed,omitzero"`
	// Total amount repaid across all repay events.
	TotalRepaid optionalnullable.OptionalNullable[string] `json:"total_repaid,omitzero"`
	// Interest paid on debt: on_chain_balance + total_repaid - total_borrowed.
	InterestPaid optionalnullable.OptionalNullable[string] `json:"interest_paid,omitzero"`
	// All historical events for this debt reserve.
	Events []CreditEvent `json:"events,omitzero"`
}

func (d DebtPosition) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DebtPosition) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DebtPosition) GetToken() string {
	if d == nil {
		return ""
	}
	return d.Token
}

func (d *DebtPosition) GetSymbol() string {
	if d == nil {
		return ""
	}
	return d.Symbol
}

func (d *DebtPosition) GetProtocol() *CreditProtocol {
	if d == nil {
		return nil
	}
	return d.Protocol
}

func (d *DebtPosition) GetVault() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.Vault
}

func (d *DebtPosition) GetSubAccountID() optionalnullable.OptionalNullable[int64] {
	if d == nil {
		return nil
	}
	return d.SubAccountID
}

func (d *DebtPosition) GetMarketID() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.MarketID
}

func (d *DebtPosition) GetHealthFactor() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.HealthFactor
}

func (d *DebtPosition) GetAmountBorrowed() *string {
	if d == nil {
		return nil
	}
	return d.AmountBorrowed
}

func (d *DebtPosition) GetUsdValue() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.UsdValue
}

func (d *DebtPosition) GetBorrowApy() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.BorrowApy
}

func (d *DebtPosition) GetTotalBorrowed() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.TotalBorrowed
}

func (d *DebtPosition) GetTotalRepaid() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.TotalRepaid
}

func (d *DebtPosition) GetInterestPaid() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.InterestPaid
}

func (d *DebtPosition) GetEvents() []CreditEvent {
	if d == nil {
		return nil
	}
	return d.Events
}
