// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DexPoolsResponse struct {
	Total  int64         `json:"total"`
	Offset int64         `json:"offset"`
	Limit  int64         `json:"limit"`
	Pools  []DexPoolInfo `json:"pools"`
}

func (d *DexPoolsResponse) GetTotal() int64 {
	if d == nil {
		return 0
	}
	return d.Total
}

func (d *DexPoolsResponse) GetOffset() int64 {
	if d == nil {
		return 0
	}
	return d.Offset
}

func (d *DexPoolsResponse) GetLimit() int64 {
	if d == nil {
		return 0
	}
	return d.Limit
}

func (d *DexPoolsResponse) GetPools() []DexPoolInfo {
	if d == nil {
		return []DexPoolInfo{}
	}
	return d.Pools
}
