// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DexVersion - Which Uniswap deployment a pool belongs to.
//
// v3 pools hold their own tokens and pay LPs the fee tier. v4 pools live in a
// shared PoolManager and may route the fee through a hook, which is where the
// launchpad pools' zero LP yield comes from.
type DexVersion string

const (
	DexVersionV3 DexVersion = "V3"
	DexVersionV4 DexVersion = "V4"
)

func (e DexVersion) ToPointer() *DexVersion {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DexVersion) IsExact() bool {
	if e != nil {
		switch *e {
		case "V3", "V4":
			return true
		}
	}
	return false
}
