// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
	"github.com/CompassLabs/cli/internal/sdk/types"
)

// FullRange - The whole price range: never out of range, and never concentrated.
type FullRange struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ *string `const:"full" json:"type,omitzero"`
}

func (f FullRange) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FullRange) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FullRange) GetType() *string {
	return types.Pointer("full")
}
