// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GlobalMarketsPerpsDepositResponse - EIP-2612 permit data for the user to sign, plus deposit metadata.
//
// After the user signs the permit, the gas sponsor calls
// batchedDepositWithPermit on the Hyperliquid Bridge2 contract.
type GlobalMarketsPerpsDepositResponse struct {
	// Response containing EIP-712 typed data for ERC-20 Permit signing.
	Permit PermitTypedDataResponseOutput `json:"permit"`
	// USDC amount in raw units (6 decimals)
	AmountRaw int64 `json:"amount_raw"`
	// Global Markets Perps Safe address on HyperEVM that receives the deposit on HyperCore
	Destination string `json:"destination"`
}

func (g *GlobalMarketsPerpsDepositResponse) GetPermit() PermitTypedDataResponseOutput {
	if g == nil {
		return PermitTypedDataResponseOutput{}
	}
	return g.Permit
}

func (g *GlobalMarketsPerpsDepositResponse) GetAmountRaw() int64 {
	if g == nil {
		return 0
	}
	return g.AmountRaw
}

func (g *GlobalMarketsPerpsDepositResponse) GetDestination() string {
	if g == nil {
		return ""
	}
	return g.Destination
}
