// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

// GlobalMarketsPerpsEnsureLeverageResponse - Returned by the ensure_leverage endpoint.
//
// If the asset is already at 1x cross leverage, typed_data/action/nonce are null.
// If not (or no position exists), they contain the EIP-712 payload the user must sign.
type GlobalMarketsPerpsEnsureLeverageResponse struct {
	// True if leverage is already 1x cross, false if update needed
	LeverageOk bool `json:"leverage_ok"`
	// EIP-712 typed data for wallet signing, or null if already 1x cross
	TypedData optionalnullable.OptionalNullable[map[string]any] `json:"typed_data,omitzero"`
	// Raw Hyperliquid action (passed back to the execute endpoint), or null
	Action optionalnullable.OptionalNullable[map[string]any] `json:"action,omitzero"`
	// Timestamp-based nonce, or null if no action needed
	Nonce optionalnullable.OptionalNullable[int64] `json:"nonce,omitzero"`
}

func (g GlobalMarketsPerpsEnsureLeverageResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GlobalMarketsPerpsEnsureLeverageResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GlobalMarketsPerpsEnsureLeverageResponse) GetLeverageOk() bool {
	if g == nil {
		return false
	}
	return g.LeverageOk
}

func (g *GlobalMarketsPerpsEnsureLeverageResponse) GetTypedData() optionalnullable.OptionalNullable[map[string]any] {
	if g == nil {
		return nil
	}
	return g.TypedData
}

func (g *GlobalMarketsPerpsEnsureLeverageResponse) GetAction() optionalnullable.OptionalNullable[map[string]any] {
	if g == nil {
		return nil
	}
	return g.Action
}

func (g *GlobalMarketsPerpsEnsureLeverageResponse) GetNonce() optionalnullable.OptionalNullable[int64] {
	if g == nil {
		return nil
	}
	return g.Nonce
}
