// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GlobalMarketsPerpsEnsureLeverageRequest - Request to check and set leverage to 1x cross on a global markets perps asset.
type GlobalMarketsPerpsEnsureLeverageRequest struct {
	// User's EOA address
	Owner string `json:"owner"`
	// Asset ticker (e.g. 'AAPL', 'CL')
	Asset string `json:"asset"`
}

func (g *GlobalMarketsPerpsEnsureLeverageRequest) GetOwner() string {
	if g == nil {
		return ""
	}
	return g.Owner
}

func (g *GlobalMarketsPerpsEnsureLeverageRequest) GetAsset() string {
	if g == nil {
		return ""
	}
	return g.Asset
}
