// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
)

// GlobalMarketsPerpsLimitOrderRequest - Request to place a limit order on a global markets perps market.
type GlobalMarketsPerpsLimitOrderRequest struct {
	// Owner of the global markets perps product account
	Owner string `json:"owner"`
	// Asset ticker symbol (e.g. AAPL, GOLD, EUR)
	Asset string `json:"asset"`
	// Order side: 'buy' or 'sell'
	Side string `json:"side"`
	// Number of contracts (human-readable)
	Size string `json:"size"`
	// Limit price (human-readable)
	Price string `json:"price"`
	// Time-in-force: 'gtc' (good til cancel) or 'alo' (add liquidity only)
	TimeInForce *string `json:"time_in_force,omitzero"`
	// If true, order can only reduce an existing position
	ReduceOnly *bool `json:"reduce_only,omitzero"`
	// Optional client order ID for idempotency (uint128)
	ClientOrderID optionalnullable.OptionalNullable[int64] `json:"client_order_id,omitzero"`
}

func (g *GlobalMarketsPerpsLimitOrderRequest) GetOwner() string {
	if g == nil {
		return ""
	}
	return g.Owner
}

func (g *GlobalMarketsPerpsLimitOrderRequest) GetAsset() string {
	if g == nil {
		return ""
	}
	return g.Asset
}

func (g *GlobalMarketsPerpsLimitOrderRequest) GetSide() string {
	if g == nil {
		return ""
	}
	return g.Side
}

func (g *GlobalMarketsPerpsLimitOrderRequest) GetSize() string {
	if g == nil {
		return ""
	}
	return g.Size
}

func (g *GlobalMarketsPerpsLimitOrderRequest) GetPrice() string {
	if g == nil {
		return ""
	}
	return g.Price
}

func (g *GlobalMarketsPerpsLimitOrderRequest) GetTimeInForce() *string {
	if g == nil {
		return nil
	}
	return g.TimeInForce
}

func (g *GlobalMarketsPerpsLimitOrderRequest) GetReduceOnly() *bool {
	if g == nil {
		return nil
	}
	return g.ReduceOnly
}

func (g *GlobalMarketsPerpsLimitOrderRequest) GetClientOrderID() optionalnullable.OptionalNullable[int64] {
	if g == nil {
		return nil
	}
	return g.ClientOrderID
}
