// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
)

// GlobalMarketsPerpsPositionSide - Position side: 'long' or 'short'
type GlobalMarketsPerpsPositionSide string

const (
	GlobalMarketsPerpsPositionSideLong  GlobalMarketsPerpsPositionSide = "long"
	GlobalMarketsPerpsPositionSideShort GlobalMarketsPerpsPositionSide = "short"
)

func (e GlobalMarketsPerpsPositionSide) ToPointer() *GlobalMarketsPerpsPositionSide {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GlobalMarketsPerpsPositionSide) IsExact() bool {
	if e != nil {
		switch *e {
		case "long", "short":
			return true
		}
	}
	return false
}

// GlobalMarketsPerpsPosition - A single open perpetual futures position.
type GlobalMarketsPerpsPosition struct {
	// Asset ticker symbol
	Asset string `json:"asset"`
	// Hyperliquid asset index
	AssetID int64 `json:"asset_id"`
	// Position side: 'long' or 'short'
	Side GlobalMarketsPerpsPositionSide `json:"side"`
	// Position size in contracts
	Size string `json:"size"`
	// Average entry price
	EntryPrice string `json:"entry_price"`
	// Current mark price
	MarkPrice string `json:"mark_price"`
	// Estimated liquidation price
	LiquidationPrice optionalnullable.OptionalNullable[string] `json:"liquidation_price,omitzero"`
	// Unrealized PnL in USD
	UnrealizedPnl string `json:"unrealized_pnl"`
	// Current leverage
	Leverage string `json:"leverage"`
	// Margin used for this position in USD
	MarginUsed string `json:"margin_used"`
	// Cumulative funding payments (negative = paid)
	FundingAccrued string `json:"funding_accrued"`
}

func (g *GlobalMarketsPerpsPosition) GetAsset() string {
	if g == nil {
		return ""
	}
	return g.Asset
}

func (g *GlobalMarketsPerpsPosition) GetAssetID() int64 {
	if g == nil {
		return 0
	}
	return g.AssetID
}

func (g *GlobalMarketsPerpsPosition) GetSide() GlobalMarketsPerpsPositionSide {
	if g == nil {
		return GlobalMarketsPerpsPositionSide("")
	}
	return g.Side
}

func (g *GlobalMarketsPerpsPosition) GetSize() string {
	if g == nil {
		return ""
	}
	return g.Size
}

func (g *GlobalMarketsPerpsPosition) GetEntryPrice() string {
	if g == nil {
		return ""
	}
	return g.EntryPrice
}

func (g *GlobalMarketsPerpsPosition) GetMarkPrice() string {
	if g == nil {
		return ""
	}
	return g.MarkPrice
}

func (g *GlobalMarketsPerpsPosition) GetLiquidationPrice() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.LiquidationPrice
}

func (g *GlobalMarketsPerpsPosition) GetUnrealizedPnl() string {
	if g == nil {
		return ""
	}
	return g.UnrealizedPnl
}

func (g *GlobalMarketsPerpsPosition) GetLeverage() string {
	if g == nil {
		return ""
	}
	return g.Leverage
}

func (g *GlobalMarketsPerpsPosition) GetMarginUsed() string {
	if g == nil {
		return ""
	}
	return g.MarginUsed
}

func (g *GlobalMarketsPerpsPosition) GetFundingAccrued() string {
	if g == nil {
		return ""
	}
	return g.FundingAccrued
}
