// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GlobalMarketsPerpsApproveBuilderFeeRequest - Request to approve builder fees before trading on the global markets perps DEX.
type GlobalMarketsPerpsApproveBuilderFeeRequest struct {
	// User's EOA address
	Owner string `json:"owner"`
	// Builder address + max fee rate the end-user authorizes.
	Builder Builder `json:"builder"`
}

func (g *GlobalMarketsPerpsApproveBuilderFeeRequest) GetOwner() string {
	if g == nil {
		return ""
	}
	return g.Owner
}

func (g *GlobalMarketsPerpsApproveBuilderFeeRequest) GetBuilder() Builder {
	if g == nil {
		return Builder{}
	}
	return g.Builder
}
