// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GlobalMarketsPerpsSignableActionResponse - Returned by prepare endpoints — contains EIP-712 typed data for the user to sign.
type GlobalMarketsPerpsSignableActionResponse struct {
	// EIP-712 typed data for wallet signing (domain, types, primaryType, message)
	TypedData map[string]any `json:"typed_data"`
	// Raw Hyperliquid action (passed back to the execute endpoint)
	Action map[string]any `json:"action"`
	// Timestamp-based nonce used during signing
	Nonce int64 `json:"nonce"`
}

func (g *GlobalMarketsPerpsSignableActionResponse) GetTypedData() map[string]any {
	if g == nil {
		return map[string]any{}
	}
	return g.TypedData
}

func (g *GlobalMarketsPerpsSignableActionResponse) GetAction() map[string]any {
	if g == nil {
		return map[string]any{}
	}
	return g.Action
}

func (g *GlobalMarketsPerpsSignableActionResponse) GetNonce() int64 {
	if g == nil {
		return 0
	}
	return g.Nonce
}
