// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// Generated under the AGPL-3.0-only license.
// SPDX-License-Identifier: AGPL-3.0-only

package components

import (
	"net/http"
)

type HTTPMetadata struct {
	// Raw HTTP response; suitable for custom response parsing
	Response *http.Response `json:"-"`
	// Raw HTTP request; suitable for debugging
	Request *http.Request `json:"-"`
}

func (h *HTTPMetadata) GetResponse() *http.Response {
	if h == nil {
		return nil
	}
	return h.Response
}

func (h *HTTPMetadata) GetRequest() *http.Request {
	if h == nil {
		return nil
	}
	return h.Request
}
