// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
)

// LoopedPositionPnl - What a looped position has made or lost since it opened.
//
// Measured in the position's debt token (the quote), with USD alongside.
// Every transaction is an equity flow valued when it landed: a loop's
// principal goes in, an unwind's proceeds come out. PnL is what the position
// is worth now plus everything taken out, minus everything put in; each
// history entry carries its own flow in equity_flow_quote.
type LoopedPositionPnl struct {
	// Profit or loss since the position opened, in the position's debt token: what the position is worth now, plus everything taken out, minus everything put in, each valued when it happened. It includes the entry and exit swap costs, the carry (what the collateral earned minus the interest paid) and the collateral's price move against the debt token. Realized once the position is closed, unrealized while it is open. Where a loop or unwind's own swap could not be used (its history entry has flow_basis 'oracle'), that swap's cost is not counted and the figure reads higher by roughly that amount.
	//
	// Measured in the debt token, not USD: on a correlated loop (wstHYPE against WHYPE, wstETH against WETH) a positive figure here can still be a USD loss when the debt token itself falls. total_pnl_usd carries that.
	TotalPnlQuote *string `json:"total_pnl_quote"`
	// total_pnl_quote as a percentage of the equity put in (e.g. 4.2 = 4.2%): the return on the capital contributed, not annualized.
	TotalPnlPercent optionalnullable.OptionalNullable[string] `json:"total_pnl_percent,omitzero"`
	// Profit or loss since the position opened, in USD: each flow at the debt token's USD price when it happened, the position's current value at its price now. Unlike total_pnl_quote it includes the debt token's own USD move. Null when any of those prices is unavailable.
	TotalPnlUsd optionalnullable.OptionalNullable[string] `json:"total_pnl_usd,omitzero"`
}

func (l *LoopedPositionPnl) GetTotalPnlQuote() *string {
	if l == nil {
		return nil
	}
	return l.TotalPnlQuote
}

func (l *LoopedPositionPnl) GetTotalPnlPercent() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.TotalPnlPercent
}

func (l *LoopedPositionPnl) GetTotalPnlUsd() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.TotalPnlUsd
}
