// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
)

// LoopedPositionCurrentStateHealthFactorScope - 'market' for Morpho (isolated per-market health). 'account' for Aave: collateral is pooled, so all collateral backs all debt and this health factor is shared by every Aave position on the account — see aave_account_summary for the account-level figures.
type LoopedPositionCurrentStateHealthFactorScope string

const (
	LoopedPositionCurrentStateHealthFactorScopeMarket  LoopedPositionCurrentStateHealthFactorScope = "market"
	LoopedPositionCurrentStateHealthFactorScopeAccount LoopedPositionCurrentStateHealthFactorScope = "account"
)

func (e LoopedPositionCurrentStateHealthFactorScope) ToPointer() *LoopedPositionCurrentStateHealthFactorScope {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LoopedPositionCurrentStateHealthFactorScope) IsExact() bool {
	if e != nil {
		switch *e {
		case "market", "account":
			return true
		}
	}
	return false
}

// LoopedPositionCurrentState - Live on-chain state of an OPEN looped position.
type LoopedPositionCurrentState struct {
	// Current on-chain collateral amount for this position. When multiple open Aave positions share one collateral reserve (Aave holds a single pooled aToken balance per reserve), that pooled balance is attributed across them pro-rata by each position's event-ledger contribution — bookkeeping, not protocol truth; liquidation sees the pooled account, not this per-position split.
	CollateralAmount *string `json:"collateral_amount"`
	// Current on-chain debt amount for this position.
	DebtAmount *string `json:"debt_amount"`
	// Collateral value in USD (null if unpriced). Derived from the attributed collateral_amount for shared-reserve Aave positions.
	CollateralUsd optionalnullable.OptionalNullable[string] `json:"collateral_usd,omitzero"`
	// Debt value in USD (null if unpriced).
	DebtUsd optionalnullable.OptionalNullable[string] `json:"debt_usd,omitzero"`
	// Net position value in USD (collateral - debt); null if unpriced. For shared-reserve Aave positions the collateral side uses the pro-rata attributed balance (bookkeeping, not protocol truth).
	NetUsdValue optionalnullable.OptionalNullable[string] `json:"net_usd_value,omitzero"`
	// Leverage multiplier: collateral_usd / (collateral_usd - debt_usd). Null when unpriced or net value is non-positive. For shared-reserve Aave positions this is derived from the pro-rata attributed collateral (bookkeeping, not protocol truth).
	Leverage optionalnullable.OptionalNullable[string] `json:"leverage,omitzero"`
	// Health factor. Above 1 is safe; below 1 risks liquidation. See health_factor_scope for what it covers.
	HealthFactor optionalnullable.OptionalNullable[string] `json:"health_factor,omitzero"`
	// 'market' for Morpho (isolated per-market health). 'account' for Aave: collateral is pooled, so all collateral backs all debt and this health factor is shared by every Aave position on the account — see aave_account_summary for the account-level figures.
	HealthFactorScope LoopedPositionCurrentStateHealthFactorScope `json:"health_factor_scope"`
	// What the collateral leg currently earns, in percentage (e.g. 6.12 = 6.12%). Aave: the collateral reserve's spot supply APY. Morpho: the collateral token's own yield — its 7d vault APY when it is an indexed vault share (e.g. steakUSDC); null otherwise, since Morpho collateral earns nothing from the market itself and an unindexed token's intrinsic yield is unknown.
	CollateralApy optionalnullable.OptionalNullable[string] `json:"collateral_apy,omitzero"`
	// What the debt leg currently costs, in percentage: the market's spot borrow APY (Morpho IRM rate / Aave variable borrow rate). Null when the rate read was unavailable.
	BorrowApy optionalnullable.OptionalNullable[string] `json:"borrow_apy,omitzero"`
	// Levered net yield on the position's equity, in percentage: leverage x collateral_apy - (leverage - 1) x borrow_apy. Negative means the carry is upside down (borrowing costs more than the collateral earns). Null when leverage or either leg is unknown. The collateral leg of a Morpho vault-share position is a 7d average while the borrow leg is spot.
	NetApy optionalnullable.OptionalNullable[string] `json:"net_apy,omitzero"`
}

func (l *LoopedPositionCurrentState) GetCollateralAmount() *string {
	if l == nil {
		return nil
	}
	return l.CollateralAmount
}

func (l *LoopedPositionCurrentState) GetDebtAmount() *string {
	if l == nil {
		return nil
	}
	return l.DebtAmount
}

func (l *LoopedPositionCurrentState) GetCollateralUsd() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.CollateralUsd
}

func (l *LoopedPositionCurrentState) GetDebtUsd() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.DebtUsd
}

func (l *LoopedPositionCurrentState) GetNetUsdValue() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.NetUsdValue
}

func (l *LoopedPositionCurrentState) GetLeverage() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.Leverage
}

func (l *LoopedPositionCurrentState) GetHealthFactor() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.HealthFactor
}

func (l *LoopedPositionCurrentState) GetHealthFactorScope() LoopedPositionCurrentStateHealthFactorScope {
	if l == nil {
		return LoopedPositionCurrentStateHealthFactorScope("")
	}
	return l.HealthFactorScope
}

func (l *LoopedPositionCurrentState) GetCollateralApy() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.CollateralApy
}

func (l *LoopedPositionCurrentState) GetBorrowApy() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.BorrowApy
}

func (l *LoopedPositionCurrentState) GetNetApy() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.NetApy
}
