// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// Generated under the AGPL-3.0-only license.
// SPDX-License-Identifier: AGPL-3.0-only

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

// MorphoMarketsResponse - A page of Morpho Blue lending markets, ordered + paginated on the DB set;
// each returned market is enriched with live on-chain LLTV/APY/utilisation.
type MorphoMarketsResponse struct {
	Total  int64 `json:"total"`
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
	// Morpho Blue singleton contract the markets were read from.
	Morpho string `json:"morpho"`
	// This page of lending markets (already ordered) with live LLTV, APYs, utilization, and liquidity. `total` is the full market count.
	Markets []MorphoLendingMarket `json:"markets,omitzero"`
}

func (m MorphoMarketsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MorphoMarketsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MorphoMarketsResponse) GetTotal() int64 {
	if m == nil {
		return 0
	}
	return m.Total
}

func (m *MorphoMarketsResponse) GetOffset() int64 {
	if m == nil {
		return 0
	}
	return m.Offset
}

func (m *MorphoMarketsResponse) GetLimit() int64 {
	if m == nil {
		return 0
	}
	return m.Limit
}

func (m *MorphoMarketsResponse) GetMorpho() string {
	if m == nil {
		return ""
	}
	return m.Morpho
}

func (m *MorphoMarketsResponse) GetMarkets() []MorphoLendingMarket {
	if m == nil {
		return nil
	}
	return m.Markets
}
