// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
)

// OnrampCreateRequest - Create a fiat on-ramp payment delivering USDC on Ethereum.
//
// Carries the same fields as the quote (a quote is implicit — we do not
// persist a quote handle). “quote_id“ is optional and only echoed upstream
// if Halliday's “/payments/confirm“ requires a previously-issued quote
// handle; omit it to confirm against a fresh quote.
type OnrampCreateRequest struct {
	// Amount of fiat to spend, as a decimal string (e.g. `100`).
	FiatAmount string `json:"fiat_amount"`
	// ISO-4217 fiat currency code. Defaults to `USD`.
	FiatCurrency *string `json:"fiat_currency,omitzero"`
	// The wallet that will receive the USDC on Ethereum. Funds are delivered here directly — Compass never holds them.
	DestinationAddress string `json:"destination_address"`
	// Optional Halliday quote handle to confirm against. Omit to confirm against a fresh quote derived from the amount and currency.
	QuoteID optionalnullable.OptionalNullable[string] `json:"quote_id,omitzero"`
}

func (o *OnrampCreateRequest) GetFiatAmount() string {
	if o == nil {
		return ""
	}
	return o.FiatAmount
}

func (o *OnrampCreateRequest) GetFiatCurrency() *string {
	if o == nil {
		return nil
	}
	return o.FiatCurrency
}

func (o *OnrampCreateRequest) GetDestinationAddress() string {
	if o == nil {
		return ""
	}
	return o.DestinationAddress
}

func (o *OnrampCreateRequest) GetQuoteID() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.QuoteID
}
