// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// PendleWithdrawalEvent - Pendle PT withdrawal event with cost basis at time of withdrawal.
type PendleWithdrawalEvent struct {
	// Block number when withdrawal occurred
	BlockNumber int64 `json:"block_number"`
	// Timestamp when withdrawal occurred
	BlockTimestamp time.Time `json:"block_timestamp"`
	// Transaction hash of the withdrawal
	TransactionHash string `json:"transaction_hash"`
	// PT tokens sold/redeemed
	InputAmount string `json:"input_amount"`
	// Symbol (PT)
	InputSymbol string `json:"input_symbol"`
	// Amount received (SY or token)
	OutputAmount string `json:"output_amount"`
	// Symbol of token received
	OutputSymbol string `json:"output_symbol"`
	// Profit/loss: output value - cost basis consumed
	RealizedPnl string `json:"realized_pnl"`
	// Cost basis per PT at withdrawal (SY received per PT sold)
	CostPerUnit string `json:"cost_per_unit"`
}

func (p PendleWithdrawalEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PendleWithdrawalEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PendleWithdrawalEvent) GetBlockNumber() int64 {
	if p == nil {
		return 0
	}
	return p.BlockNumber
}

func (p *PendleWithdrawalEvent) GetBlockTimestamp() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.BlockTimestamp
}

func (p *PendleWithdrawalEvent) GetTransactionHash() string {
	if p == nil {
		return ""
	}
	return p.TransactionHash
}

func (p *PendleWithdrawalEvent) GetInputAmount() string {
	if p == nil {
		return ""
	}
	return p.InputAmount
}

func (p *PendleWithdrawalEvent) GetInputSymbol() string {
	if p == nil {
		return ""
	}
	return p.InputSymbol
}

func (p *PendleWithdrawalEvent) GetOutputAmount() string {
	if p == nil {
		return ""
	}
	return p.OutputAmount
}

func (p *PendleWithdrawalEvent) GetOutputSymbol() string {
	if p == nil {
		return ""
	}
	return p.OutputSymbol
}

func (p *PendleWithdrawalEvent) GetRealizedPnl() string {
	if p == nil {
		return ""
	}
	return p.RealizedPnl
}

func (p *PendleWithdrawalEvent) GetCostPerUnit() string {
	if p == nil {
		return ""
	}
	return p.CostPerUnit
}
