// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// PendleDepositEvent - Pendle PT deposit event with cost basis at time of deposit.
type PendleDepositEvent struct {
	// Block number when deposit occurred
	BlockNumber int64 `json:"block_number"`
	// Timestamp when deposit occurred
	BlockTimestamp time.Time `json:"block_timestamp"`
	// Transaction hash of the deposit
	TransactionHash string `json:"transaction_hash"`
	// Amount deposited (token spent)
	InputAmount string `json:"input_amount"`
	// Symbol of token deposited
	InputSymbol string `json:"input_symbol"`
	// PT tokens received
	OutputAmount string `json:"output_amount"`
	// Symbol (PT)
	OutputSymbol string `json:"output_symbol"`
	// Cost basis per PT at deposit (SY spent per PT acquired)
	CostPerUnit string `json:"cost_per_unit"`
}

func (p PendleDepositEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PendleDepositEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PendleDepositEvent) GetBlockNumber() int64 {
	if p == nil {
		return 0
	}
	return p.BlockNumber
}

func (p *PendleDepositEvent) GetBlockTimestamp() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.BlockTimestamp
}

func (p *PendleDepositEvent) GetTransactionHash() string {
	if p == nil {
		return ""
	}
	return p.TransactionHash
}

func (p *PendleDepositEvent) GetInputAmount() string {
	if p == nil {
		return ""
	}
	return p.InputAmount
}

func (p *PendleDepositEvent) GetInputSymbol() string {
	if p == nil {
		return ""
	}
	return p.InputSymbol
}

func (p *PendleDepositEvent) GetOutputAmount() string {
	if p == nil {
		return ""
	}
	return p.OutputAmount
}

func (p *PendleDepositEvent) GetOutputSymbol() string {
	if p == nil {
		return ""
	}
	return p.OutputSymbol
}

func (p *PendleDepositEvent) GetCostPerUnit() string {
	if p == nil {
		return ""
	}
	return p.CostPerUnit
}
