// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

// PermitTypedDataResponseOutput - Response containing EIP-712 typed data for ERC-20 Permit signing.
type PermitTypedDataResponseOutput struct {
	// The EIP-712 domain separator for ERC-20 Permit.
	Domain CompassAPIBackendV2ModelsGasSponsorshipPermitTypedDataEip712Domain `json:"domain"`
	// The type definitions for EIP-712 structured data (ERC-20 Permit).
	Types CompassAPIBackendV2ModelsGasSponsorshipPermitTypedDataEip712Types `json:"types"`
	// Primary type for the structured data
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	primaryType string `const:"Permit" json:"primaryType"`
	// The message data for an ERC-20 Permit.
	Message PermitMessage `json:"message"`
}

func (p PermitTypedDataResponseOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PermitTypedDataResponseOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PermitTypedDataResponseOutput) GetDomain() CompassAPIBackendV2ModelsGasSponsorshipPermitTypedDataEip712Domain {
	if p == nil {
		return CompassAPIBackendV2ModelsGasSponsorshipPermitTypedDataEip712Domain{}
	}
	return p.Domain
}

func (p *PermitTypedDataResponseOutput) GetTypes() CompassAPIBackendV2ModelsGasSponsorshipPermitTypedDataEip712Types {
	if p == nil {
		return CompassAPIBackendV2ModelsGasSponsorshipPermitTypedDataEip712Types{}
	}
	return p.Types
}

func (p *PermitTypedDataResponseOutput) GetPrimaryType() string {
	return "Permit"
}

func (p *PermitTypedDataResponseOutput) GetMessage() PermitMessage {
	if p == nil {
		return PermitMessage{}
	}
	return p.Message
}
