// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
	"github.com/CompassLabs/cli/internal/sdk/types"
)

type Permit2TypedDataInput struct {
	Types CompassAPIBackendV2ModelsGasSponsorshipPermit2TypedDataEip712Types `json:"types"`
	// Root type for signing
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	primaryType *string                                                             `const:"PermitTransferFrom" json:"primaryType,omitzero"`
	Domain      CompassAPIBackendV2ModelsGasSponsorshipPermit2TypedDataEip712Domain `json:"domain"`
	Message     PermitTransferFromMessage                                           `json:"message"`
}

func (p Permit2TypedDataInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Permit2TypedDataInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Permit2TypedDataInput) GetTypes() CompassAPIBackendV2ModelsGasSponsorshipPermit2TypedDataEip712Types {
	if p == nil {
		return CompassAPIBackendV2ModelsGasSponsorshipPermit2TypedDataEip712Types{}
	}
	return p.Types
}

func (p *Permit2TypedDataInput) GetPrimaryType() *string {
	return types.Pointer("PermitTransferFrom")
}

func (p *Permit2TypedDataInput) GetDomain() CompassAPIBackendV2ModelsGasSponsorshipPermit2TypedDataEip712Domain {
	if p == nil {
		return CompassAPIBackendV2ModelsGasSponsorshipPermit2TypedDataEip712Domain{}
	}
	return p.Domain
}

func (p *Permit2TypedDataInput) GetMessage() PermitTransferFromMessage {
	if p == nil {
		return PermitTransferFromMessage{}
	}
	return p.Message
}

// #region class-body-permit2typeddatainput
// #endregion class-body-permit2typeddatainput
