// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// Generated under the AGPL-3.0-only license.
// SPDX-License-Identifier: AGPL-3.0-only

package components

// PerpetualTradingOpenOrderSide - Order side
type PerpetualTradingOpenOrderSide string

const (
	PerpetualTradingOpenOrderSideBuy  PerpetualTradingOpenOrderSide = "buy"
	PerpetualTradingOpenOrderSideSell PerpetualTradingOpenOrderSide = "sell"
)

func (e PerpetualTradingOpenOrderSide) ToPointer() *PerpetualTradingOpenOrderSide {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PerpetualTradingOpenOrderSide) IsExact() bool {
	if e != nil {
		switch *e {
		case "buy", "sell":
			return true
		}
	}
	return false
}

// PerpetualTradingOpenOrder - A single resting order from HL `openOrders`.
type PerpetualTradingOpenOrder struct {
	// Asset ticker symbol (xyz prefix stripped)
	Asset string `json:"asset"`
	// Order side
	Side PerpetualTradingOpenOrderSide `json:"side"`
	// Limit price
	LimitPrice string `json:"limit_price"`
	// Order size in contracts
	Size string `json:"size"`
	// HL order id (oid)
	OrderID int64 `json:"order_id"`
	// Order timestamp (ms since epoch)
	TimeMs int64 `json:"time_ms"`
	// True if order can only reduce position
	ReduceOnly bool `json:"reduce_only"`
}

func (p *PerpetualTradingOpenOrder) GetAsset() string {
	if p == nil {
		return ""
	}
	return p.Asset
}

func (p *PerpetualTradingOpenOrder) GetSide() PerpetualTradingOpenOrderSide {
	if p == nil {
		return PerpetualTradingOpenOrderSide("")
	}
	return p.Side
}

func (p *PerpetualTradingOpenOrder) GetLimitPrice() string {
	if p == nil {
		return ""
	}
	return p.LimitPrice
}

func (p *PerpetualTradingOpenOrder) GetSize() string {
	if p == nil {
		return ""
	}
	return p.Size
}

func (p *PerpetualTradingOpenOrder) GetOrderID() int64 {
	if p == nil {
		return 0
	}
	return p.OrderID
}

func (p *PerpetualTradingOpenOrder) GetTimeMs() int64 {
	if p == nil {
		return 0
	}
	return p.TimeMs
}

func (p *PerpetualTradingOpenOrder) GetReduceOnly() bool {
	if p == nil {
		return false
	}
	return p.ReduceOnly
}
