// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
)

// PerpetualTradingWithdrawRequest - Request to withdraw USDC from HyperEVM perpetual trading account to Arbitrum.
type PerpetualTradingWithdrawRequest struct {
	// The user's EOA address (owner of the perpetual trading account)
	Owner string `json:"owner"`
	// USDC amount to withdraw (human-readable, e.g. '500.0')
	Amount string `json:"amount"`
	// Arbitrum destination address (defaults to owner if not specified)
	Destination optionalnullable.OptionalNullable[string] `json:"destination,omitzero"`
}

func (p *PerpetualTradingWithdrawRequest) GetOwner() string {
	if p == nil {
		return ""
	}
	return p.Owner
}

func (p *PerpetualTradingWithdrawRequest) GetAmount() string {
	if p == nil {
		return ""
	}
	return p.Amount
}

func (p *PerpetualTradingWithdrawRequest) GetDestination() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Destination
}
