// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// Generated under the AGPL-3.0-only license.
// SPDX-License-Identifier: AGPL-3.0-only

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
)

// PerpetualTradingCancelOrderRequest - Request to cancel an open order on a perpetual trading market.
type PerpetualTradingCancelOrderRequest struct {
	// Owner of the perpetual trading product account
	Owner string `json:"owner"`
	// Asset ticker symbol (e.g. AAPL, GOLD, EUR)
	Asset string `json:"asset"`
	// Hyperliquid order ID to cancel
	OrderID optionalnullable.OptionalNullable[int64] `json:"order_id,omitzero"`
	// Client order ID to cancel (alternative to order_id)
	ClientOrderID optionalnullable.OptionalNullable[int64] `json:"client_order_id,omitzero"`
}

func (p *PerpetualTradingCancelOrderRequest) GetOwner() string {
	if p == nil {
		return ""
	}
	return p.Owner
}

func (p *PerpetualTradingCancelOrderRequest) GetAsset() string {
	if p == nil {
		return ""
	}
	return p.Asset
}

func (p *PerpetualTradingCancelOrderRequest) GetOrderID() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.OrderID
}

func (p *PerpetualTradingCancelOrderRequest) GetClientOrderID() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.ClientOrderID
}
