// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
)

// PlanStep - One leg of a bundled transaction, in the order it executes.
//
// Every transact endpoint returns a single transaction; this is what is inside
// it, so a caller can show a person what they are about to sign.
type PlanStep struct {
	Kind        PlanStepKind                              `json:"kind"`
	Description string                                    `json:"description"`
	Contract    optionalnullable.OptionalNullable[string] `json:"contract,omitzero"`
	Token       optionalnullable.OptionalNullable[string] `json:"token,omitzero"`
	Amount      optionalnullable.OptionalNullable[string] `json:"amount,omitzero"`
}

func (p *PlanStep) GetKind() PlanStepKind {
	if p == nil {
		return PlanStepKind("")
	}
	return p.Kind
}

func (p *PlanStep) GetDescription() string {
	if p == nil {
		return ""
	}
	return p.Description
}

func (p *PlanStep) GetContract() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Contract
}

func (p *PlanStep) GetToken() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Token
}

func (p *PlanStep) GetAmount() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Amount
}
