// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ProbabilisticOutlook - How likely the outcomes are, not just how large.
type ProbabilisticOutlook struct {
	Method string `json:"method"`
	Paths  int64  `json:"paths"`
	// The chance the price *touches* a bound at any point, not just ends outside it. A position that left the range and came back still stopped earning while it was out.
	PExitWithinHorizonPct  string            `json:"p_exit_within_horizon_pct"`
	POutAtHorizonPct       string            `json:"p_out_at_horizon_pct"`
	ExpectedTimeInRangePct string            `json:"expected_time_in_range_pct"`
	ExpectedIlUsd          string            `json:"expected_il_usd"`
	ExpectedNetPnlUsd      string            `json:"expected_net_pnl_usd"`
	ProbNetLossPct         string            `json:"prob_net_loss_pct"`
	IlPctPercentiles       map[string]string `json:"il_pct_percentiles"`
	IlUsdPercentiles       map[string]string `json:"il_usd_percentiles"`
	NetPnlUsdPercentiles   map[string]string `json:"net_pnl_usd_percentiles"`
}

func (p *ProbabilisticOutlook) GetMethod() string {
	if p == nil {
		return ""
	}
	return p.Method
}

func (p *ProbabilisticOutlook) GetPaths() int64 {
	if p == nil {
		return 0
	}
	return p.Paths
}

func (p *ProbabilisticOutlook) GetPExitWithinHorizonPct() string {
	if p == nil {
		return ""
	}
	return p.PExitWithinHorizonPct
}

func (p *ProbabilisticOutlook) GetPOutAtHorizonPct() string {
	if p == nil {
		return ""
	}
	return p.POutAtHorizonPct
}

func (p *ProbabilisticOutlook) GetExpectedTimeInRangePct() string {
	if p == nil {
		return ""
	}
	return p.ExpectedTimeInRangePct
}

func (p *ProbabilisticOutlook) GetExpectedIlUsd() string {
	if p == nil {
		return ""
	}
	return p.ExpectedIlUsd
}

func (p *ProbabilisticOutlook) GetExpectedNetPnlUsd() string {
	if p == nil {
		return ""
	}
	return p.ExpectedNetPnlUsd
}

func (p *ProbabilisticOutlook) GetProbNetLossPct() string {
	if p == nil {
		return ""
	}
	return p.ProbNetLossPct
}

func (p *ProbabilisticOutlook) GetIlPctPercentiles() map[string]string {
	if p == nil {
		return map[string]string{}
	}
	return p.IlPctPercentiles
}

func (p *ProbabilisticOutlook) GetIlUsdPercentiles() map[string]string {
	if p == nil {
		return map[string]string{}
	}
	return p.IlUsdPercentiles
}

func (p *ProbabilisticOutlook) GetNetPnlUsdPercentiles() map[string]string {
	if p == nil {
		return map[string]string{}
	}
	return p.NetPnlUsdPercentiles
}
