// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

// RebalancePhase - One stage of the plan, with the legs it contributes.
type RebalancePhase struct {
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Steps       []PlanStep `json:"steps,omitzero"`
}

func (r RebalancePhase) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RebalancePhase) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RebalancePhase) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RebalancePhase) GetDescription() string {
	if r == nil {
		return ""
	}
	return r.Description
}

func (r *RebalancePhase) GetSteps() []PlanStep {
	if r == nil {
		return nil
	}
	return r.Steps
}
