// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
)

// RedemptionStatus - Lifecycle state: `pending` (awaiting operator settlement), `finalized` (settled — assets paid to the product account), `rejected` (operator declined; shares returned to the account), or `unknown` (an unrecognized on-chain status code — should not occur for the current contract, surfaced defensively instead of erroring).
type RedemptionStatus string

const (
	RedemptionStatusPending   RedemptionStatus = "pending"
	RedemptionStatusFinalized RedemptionStatus = "finalized"
	RedemptionStatusRejected  RedemptionStatus = "rejected"
	RedemptionStatusUnknown   RedemptionStatus = "unknown"
)

func (e RedemptionStatus) ToPointer() *RedemptionStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *RedemptionStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "finalized", "rejected", "unknown":
			return true
		}
	}
	return false
}

// Redemption - One IXS vault redemption request, reconstructed on-chain.
type Redemption struct {
	// On-chain redemption request id.
	ID int64 `json:"id"`
	// Lifecycle state: `pending` (awaiting operator settlement), `finalized` (settled — assets paid to the product account), `rejected` (operator declined; shares returned to the account), or `unknown` (an unrecognized on-chain status code — should not occur for the current contract, surfaced defensively instead of erroring).
	Status RedemptionStatus `json:"status"`
	// Vault shares in the request (human units).
	Shares string `json:"shares"`
	// For a `pending` request, the estimated net assets (after the exit fee) it would settle for at the current NAV — a preview, not a guarantee (settlement depends on the operator and the vault's available assets). Null once finalized or rejected.
	ExpectedNetAssets optionalnullable.OptionalNullable[string] `json:"expected_net_assets,omitzero"`
	// Unix timestamp when the redemption was requested.
	RequestedAt int64 `json:"requested_at"`
	// Unix timestamp when finalized/rejected; null while pending.
	ProcessedAt optionalnullable.OptionalNullable[int64] `json:"processed_at,omitzero"`
}

func (r *Redemption) GetID() int64 {
	if r == nil {
		return 0
	}
	return r.ID
}

func (r *Redemption) GetStatus() RedemptionStatus {
	if r == nil {
		return RedemptionStatus("")
	}
	return r.Status
}

func (r *Redemption) GetShares() string {
	if r == nil {
		return ""
	}
	return r.Shares
}

func (r *Redemption) GetExpectedNetAssets() optionalnullable.OptionalNullable[string] {
	if r == nil {
		return nil
	}
	return r.ExpectedNetAssets
}

func (r *Redemption) GetRequestedAt() int64 {
	if r == nil {
		return 0
	}
	return r.RequestedAt
}

func (r *Redemption) GetProcessedAt() optionalnullable.OptionalNullable[int64] {
	if r == nil {
		return nil
	}
	return r.ProcessedAt
}
