// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

// RiskYieldIncreaseRequestChain - Risk Yield is available on Robinhood Chain only.
type RiskYieldIncreaseRequestChain string

const (
	RiskYieldIncreaseRequestChainRobinhood RiskYieldIncreaseRequestChain = "robinhood"
)

func (e RiskYieldIncreaseRequestChain) ToPointer() *RiskYieldIncreaseRequestChain {
	return &e
}
func (e *RiskYieldIncreaseRequestChain) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "robinhood":
		*e = RiskYieldIncreaseRequestChain(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RiskYieldIncreaseRequestChain: %v", v)
	}
}

type RiskYieldIncreaseRequestSlippagePctType string

const (
	RiskYieldIncreaseRequestSlippagePctTypeNumber RiskYieldIncreaseRequestSlippagePctType = "number"
	RiskYieldIncreaseRequestSlippagePctTypeStr    RiskYieldIncreaseRequestSlippagePctType = "str"
)

// RiskYieldIncreaseRequestSlippagePct - How far the executed amounts may fall short of the quote before the transaction reverts. Memecoin pools move between the quote and the block that includes the transaction.
type RiskYieldIncreaseRequestSlippagePct struct {
	Number *float64 `queryParam:"inline" union:"member"`
	Str    *string  `queryParam:"inline" union:"member"`

	Type RiskYieldIncreaseRequestSlippagePctType
}

func CreateRiskYieldIncreaseRequestSlippagePctNumber(number float64) RiskYieldIncreaseRequestSlippagePct {
	typ := RiskYieldIncreaseRequestSlippagePctTypeNumber

	return RiskYieldIncreaseRequestSlippagePct{
		Number: &number,
		Type:   typ,
	}
}

func CreateRiskYieldIncreaseRequestSlippagePctStr(str string) RiskYieldIncreaseRequestSlippagePct {
	typ := RiskYieldIncreaseRequestSlippagePctTypeStr

	return RiskYieldIncreaseRequestSlippagePct{
		Str:  &str,
		Type: typ,
	}
}

func (u *RiskYieldIncreaseRequestSlippagePct) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = RiskYieldIncreaseRequestSlippagePct{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RiskYieldIncreaseRequestSlippagePctTypeNumber,
			Value: &number,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RiskYieldIncreaseRequestSlippagePctTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for RiskYieldIncreaseRequestSlippagePct", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for RiskYieldIncreaseRequestSlippagePct", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(RiskYieldIncreaseRequestSlippagePctType)
	switch best.Type {
	case RiskYieldIncreaseRequestSlippagePctTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case RiskYieldIncreaseRequestSlippagePctTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RiskYieldIncreaseRequestSlippagePct", string(data))
}

func (u RiskYieldIncreaseRequestSlippagePct) MarshalJSON() ([]byte, error) {
	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type RiskYieldIncreaseRequestSlippagePct: all fields are null")
}

type RiskYieldIncreaseRequestDepositType string

const (
	RiskYieldIncreaseRequestDepositTypeBoth   RiskYieldIncreaseRequestDepositType = "both"
	RiskYieldIncreaseRequestDepositTypeSingle RiskYieldIncreaseRequestDepositType = "single"
	RiskYieldIncreaseRequestDepositTypeUsd    RiskYieldIncreaseRequestDepositType = "usd"
)

type RiskYieldIncreaseRequestDeposit struct {
	BothSidesDeposit   *BothSidesDeposit   `queryParam:"inline" union:"member"`
	SingleSidedDeposit *SingleSidedDeposit `queryParam:"inline" union:"member"`
	UsdDeposit         *UsdDeposit         `queryParam:"inline" union:"member"`

	Type RiskYieldIncreaseRequestDepositType
}

func CreateRiskYieldIncreaseRequestDepositBoth(both BothSidesDeposit) RiskYieldIncreaseRequestDeposit {
	typ := RiskYieldIncreaseRequestDepositTypeBoth

	return RiskYieldIncreaseRequestDeposit{
		BothSidesDeposit: &both,
		Type:             typ,
	}
}

func CreateRiskYieldIncreaseRequestDepositSingle(single SingleSidedDeposit) RiskYieldIncreaseRequestDeposit {
	typ := RiskYieldIncreaseRequestDepositTypeSingle

	return RiskYieldIncreaseRequestDeposit{
		SingleSidedDeposit: &single,
		Type:               typ,
	}
}

func CreateRiskYieldIncreaseRequestDepositUsd(usd UsdDeposit) RiskYieldIncreaseRequestDeposit {
	typ := RiskYieldIncreaseRequestDepositTypeUsd

	return RiskYieldIncreaseRequestDeposit{
		UsdDeposit: &usd,
		Type:       typ,
	}
}

func (u *RiskYieldIncreaseRequestDeposit) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = RiskYieldIncreaseRequestDeposit{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "both":
		bothSidesDeposit := new(BothSidesDeposit)
		if err := utils.UnmarshalJSON(data, &bothSidesDeposit, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == both) type BothSidesDeposit within RiskYieldIncreaseRequestDeposit: %w", string(data), err)
		}

		u.BothSidesDeposit = bothSidesDeposit
		u.Type = RiskYieldIncreaseRequestDepositTypeBoth
		return nil
	case "single":
		singleSidedDeposit := new(SingleSidedDeposit)
		if err := utils.UnmarshalJSON(data, &singleSidedDeposit, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == single) type SingleSidedDeposit within RiskYieldIncreaseRequestDeposit: %w", string(data), err)
		}

		u.SingleSidedDeposit = singleSidedDeposit
		u.Type = RiskYieldIncreaseRequestDepositTypeSingle
		return nil
	case "usd":
		usdDeposit := new(UsdDeposit)
		if err := utils.UnmarshalJSON(data, &usdDeposit, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == usd) type UsdDeposit within RiskYieldIncreaseRequestDeposit: %w", string(data), err)
		}

		u.UsdDeposit = usdDeposit
		u.Type = RiskYieldIncreaseRequestDepositTypeUsd
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RiskYieldIncreaseRequestDeposit", string(data))
}

func (u RiskYieldIncreaseRequestDeposit) MarshalJSON() ([]byte, error) {
	if u.BothSidesDeposit != nil {
		return utils.MarshalJSON(u.BothSidesDeposit, "", true)
	}

	if u.SingleSidedDeposit != nil {
		return utils.MarshalJSON(u.SingleSidedDeposit, "", true)
	}

	if u.UsdDeposit != nil {
		return utils.MarshalJSON(u.UsdDeposit, "", true)
	}

	return nil, errors.New("could not marshal union type RiskYieldIncreaseRequestDeposit: all fields are null")
}

// RiskYieldIncreaseRequest - Add to a position you already hold.
type RiskYieldIncreaseRequest struct {
	// The wallet that owns the Risk Yield Account.
	Owner string `json:"owner"`
	// Risk Yield is available on Robinhood Chain only.
	Chain *RiskYieldIncreaseRequestChain `json:"chain,omitzero"`
	// Return EIP-712 typed data for the owner to sign instead of a transaction, so a sponsor can broadcast it.
	GasSponsorship *bool `json:"gas_sponsorship,omitzero"`
	// Return the plan and its simulation without building a transaction. Nothing is signed and nothing can be broadcast.
	Preview *bool `json:"preview,omitzero"`
	// How far the executed amounts may fall short of the quote before the transaction reverts. Memecoin pools move between the quote and the block that includes the transaction.
	SlippagePct *RiskYieldIncreaseRequestSlippagePct `json:"slippage_pct,omitzero"`
	// How long the transaction stays valid once built.
	DeadlineSeconds *int64 `json:"deadline_seconds,omitzero"`
	// The position NFT's id.
	PositionID int64 `json:"position_id"`
	// Which Uniswap deployment a pool belongs to.
	//
	// v3 pools hold their own tokens and pay LPs the fee tier. v4 pools live in a
	// shared PoolManager and may route the fee through a hook, which is where the
	// launchpad pools' zero LP yield comes from.
	DexVersion *DexVersion                     `json:"dex_version,omitzero"`
	Deposit    RiskYieldIncreaseRequestDeposit `json:"deposit"`
}

func (r *RiskYieldIncreaseRequest) GetOwner() string {
	if r == nil {
		return ""
	}
	return r.Owner
}

func (r *RiskYieldIncreaseRequest) GetChain() *RiskYieldIncreaseRequestChain {
	if r == nil {
		return nil
	}
	return r.Chain
}

func (r *RiskYieldIncreaseRequest) GetGasSponsorship() *bool {
	if r == nil {
		return nil
	}
	return r.GasSponsorship
}

func (r *RiskYieldIncreaseRequest) GetPreview() *bool {
	if r == nil {
		return nil
	}
	return r.Preview
}

func (r *RiskYieldIncreaseRequest) GetSlippagePct() *RiskYieldIncreaseRequestSlippagePct {
	if r == nil {
		return nil
	}
	return r.SlippagePct
}

func (r *RiskYieldIncreaseRequest) GetDeadlineSeconds() *int64 {
	if r == nil {
		return nil
	}
	return r.DeadlineSeconds
}

func (r *RiskYieldIncreaseRequest) GetPositionID() int64 {
	if r == nil {
		return 0
	}
	return r.PositionID
}

func (r *RiskYieldIncreaseRequest) GetDexVersion() *DexVersion {
	if r == nil {
		return nil
	}
	return r.DexVersion
}

func (r *RiskYieldIncreaseRequest) GetDeposit() RiskYieldIncreaseRequestDeposit {
	if r == nil {
		return RiskYieldIncreaseRequestDeposit{}
	}
	return r.Deposit
}

func (r *RiskYieldIncreaseRequest) GetDepositBoth() *BothSidesDeposit {
	return r.GetDeposit().BothSidesDeposit
}

func (r *RiskYieldIncreaseRequest) GetDepositSingle() *SingleSidedDeposit {
	return r.GetDeposit().SingleSidedDeposit
}

func (r *RiskYieldIncreaseRequest) GetDepositUsd() *UsdDeposit {
	return r.GetDeposit().UsdDeposit
}
