// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

// SafeTxField - A field in the SafeTx type definition.
type SafeTxField struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

func (s SafeTxField) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SafeTxField) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SafeTxField) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SafeTxField) GetType() string {
	if s == nil {
		return ""
	}
	return s.Type
}
