// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// Generated under the AGPL-3.0-only license.
// SPDX-License-Identifier: AGPL-3.0-only

package components

type SponsorGasResponse struct {
	Transaction UnsignedTransaction `json:"transaction"`
}

func (s *SponsorGasResponse) GetTransaction() UnsignedTransaction {
	if s == nil {
		return UnsignedTransaction{}
	}
	return s.Transaction
}
