// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// StockMetadata - The issuer's side of a tokenized stock.
//
// `ui_multiplier` is the ERC-8056 corporate-action factor. It matters because
// balances do **not** rebase on a split: the token count stays put and this
// number changes, so a price quoted for the underlying has to be multiplied by
// it to mean anything about the token a pool holds.
type StockMetadata struct {
	Ticker              string                                       `json:"ticker"`
	UIMultiplier        optionalnullable.OptionalNullable[string]    `json:"ui_multiplier,omitzero"`
	PendingUIMultiplier optionalnullable.OptionalNullable[string]    `json:"pending_ui_multiplier,omitzero"`
	PendingEffectiveAt  optionalnullable.OptionalNullable[time.Time] `json:"pending_effective_at,omitzero"`
	ChainlinkFeed       optionalnullable.OptionalNullable[string]    `json:"chainlink_feed,omitzero"`
	TokenPaused         optionalnullable.OptionalNullable[bool]      `json:"token_paused,omitzero"`
	Status              optionalnullable.OptionalNullable[string]    `json:"status,omitzero"`
	LogoURL             optionalnullable.OptionalNullable[string]    `json:"logo_url,omitzero"`
}

func (s StockMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StockMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StockMetadata) GetTicker() string {
	if s == nil {
		return ""
	}
	return s.Ticker
}

func (s *StockMetadata) GetUIMultiplier() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.UIMultiplier
}

func (s *StockMetadata) GetPendingUIMultiplier() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.PendingUIMultiplier
}

func (s *StockMetadata) GetPendingEffectiveAt() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.PendingEffectiveAt
}

func (s *StockMetadata) GetChainlinkFeed() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.ChainlinkFeed
}

func (s *StockMetadata) GetTokenPaused() optionalnullable.OptionalNullable[bool] {
	if s == nil {
		return nil
	}
	return s.TokenPaused
}

func (s *StockMetadata) GetStatus() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *StockMetadata) GetLogoURL() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.LogoURL
}
