// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
)

// SwapPlan - The swap leg of an entry or a rebalance.
type SwapPlan struct {
	TokenIn         string `json:"token_in"`
	TokenOut        string `json:"token_out"`
	AmountIn        string `json:"amount_in"`
	AmountOutQuoted string `json:"amount_out_quoted"`
	// The floor the transaction enforces, after slippage.
	AmountOutMin   string                                    `json:"amount_out_min"`
	PriceImpactPct optionalnullable.OptionalNullable[string] `json:"price_impact_pct,omitzero"`
	PoolFeePpm     optionalnullable.OptionalNullable[int64]  `json:"pool_fee_ppm,omitzero"`
}

func (s *SwapPlan) GetTokenIn() string {
	if s == nil {
		return ""
	}
	return s.TokenIn
}

func (s *SwapPlan) GetTokenOut() string {
	if s == nil {
		return ""
	}
	return s.TokenOut
}

func (s *SwapPlan) GetAmountIn() string {
	if s == nil {
		return ""
	}
	return s.AmountIn
}

func (s *SwapPlan) GetAmountOutQuoted() string {
	if s == nil {
		return ""
	}
	return s.AmountOutQuoted
}

func (s *SwapPlan) GetAmountOutMin() string {
	if s == nil {
		return ""
	}
	return s.AmountOutMin
}

func (s *SwapPlan) GetPriceImpactPct() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.PriceImpactPct
}

func (s *SwapPlan) GetPoolFeePpm() optionalnullable.OptionalNullable[int64] {
	if s == nil {
		return nil
	}
	return s.PoolFeePpm
}
