// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

// TokenizedAssetsChargeFeeResponse - Unsigned USDC fee transfer for the owner to sign.
//
// Exactly one of `transaction` (gas_sponsorship=false) or `eip_712`
// (gas_sponsorship=true) is set.
type TokenizedAssetsChargeFeeResponse struct {
	// Unsigned transaction transferring the fee from the product account.
	Transaction optionalnullable.OptionalNullable[UnsignedTransaction] `json:"transaction,omitzero"`
	// EIP-712 payload for gas-sponsored execution.
	Eip712 optionalnullable.OptionalNullable[BatchedSafeOperationsResponseOutput] `json:"eip_712,omitzero"`
	// Fee charged, in USDC.
	FeeAmount string `json:"fee_amount"`
	// Filled USDC proceeds the fee was computed on.
	Proceeds string `json:"proceeds"`
}

func (t TokenizedAssetsChargeFeeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TokenizedAssetsChargeFeeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TokenizedAssetsChargeFeeResponse) GetTransaction() optionalnullable.OptionalNullable[UnsignedTransaction] {
	if t == nil {
		return nil
	}
	return t.Transaction
}

func (t *TokenizedAssetsChargeFeeResponse) GetEip712() optionalnullable.OptionalNullable[BatchedSafeOperationsResponseOutput] {
	if t == nil {
		return nil
	}
	return t.Eip712
}

func (t *TokenizedAssetsChargeFeeResponse) GetFeeAmount() string {
	if t == nil {
		return ""
	}
	return t.FeeAmount
}

func (t *TokenizedAssetsChargeFeeResponse) GetProceeds() string {
	if t == nil {
		return ""
	}
	return t.Proceeds
}
