// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TokenizedAssetsQuoteResponse - Preview of input/output amounts plus auction-derived risk hints.
type TokenizedAssetsQuoteResponse struct {
	// Quote preview returned alongside an order.
	Quote Quote `json:"quote"`
	// Slippage tolerance in basis points (1 bp = 0.01%) the UI should echo back as `slippage_bps` on `POST /tokenized_assets/order`. Derived from Fusion's Dutch auction range (`auctionEndAmount` vs `toTokenAmount`) plus a small buffer; capped at 5000 bps.
	RecommendedSlippageBps int64 `json:"recommended_slippage_bps"`
	// Worst-case basis-points gap between the auction's end amount and the reference quote amount. Surfaces as a thin-liquidity warning before the user signs.
	AuctionRangeBps int64 `json:"auction_range_bps"`
}

func (t *TokenizedAssetsQuoteResponse) GetQuote() Quote {
	if t == nil {
		return Quote{}
	}
	return t.Quote
}

func (t *TokenizedAssetsQuoteResponse) GetRecommendedSlippageBps() int64 {
	if t == nil {
		return 0
	}
	return t.RecommendedSlippageBps
}

func (t *TokenizedAssetsQuoteResponse) GetAuctionRangeBps() int64 {
	if t == nil {
		return 0
	}
	return t.AuctionRangeBps
}
