// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

type TokenizedAssetsTransferResponseEip712Type string

const (
	TokenizedAssetsTransferResponseEip712TypeBatchedSafeOperationsResponseOutput TokenizedAssetsTransferResponseEip712Type = "BatchedSafeOperationsResponse-Output"
	TokenizedAssetsTransferResponseEip712TypePermit2TypedDataOutput              TokenizedAssetsTransferResponseEip712Type = "Permit2TypedData-Output"
	TokenizedAssetsTransferResponseEip712TypeUnknown                             TokenizedAssetsTransferResponseEip712Type = "Unknown"
)

// TokenizedAssetsTransferResponseEip712 - EIP-712 typed data for gas-sponsored execution. Present when `gas_sponsorship=true`. A Permit2 `PermitTransferFrom` for DEPOSIT, or a Safe transaction for WITHDRAW. The owner signs it and submits to `/v2/gas_sponsorship/prepare`.
type TokenizedAssetsTransferResponseEip712 struct {
	BatchedSafeOperationsResponseOutput *BatchedSafeOperationsResponseOutput `queryParam:"inline" union:"member"`
	Permit2TypedDataOutput              *Permit2TypedDataOutput              `queryParam:"inline" union:"member"`
	UnknownRaw                          json.RawMessage                      `json:"-" union:"unknown"`

	Type TokenizedAssetsTransferResponseEip712Type
}

func CreateTokenizedAssetsTransferResponseEip712BatchedSafeOperationsResponseOutput(batchedSafeOperationsResponseOutput BatchedSafeOperationsResponseOutput) TokenizedAssetsTransferResponseEip712 {
	typ := TokenizedAssetsTransferResponseEip712TypeBatchedSafeOperationsResponseOutput

	return TokenizedAssetsTransferResponseEip712{
		BatchedSafeOperationsResponseOutput: &batchedSafeOperationsResponseOutput,
		Type:                                typ,
	}
}

func CreateTokenizedAssetsTransferResponseEip712Permit2TypedDataOutput(permit2TypedDataOutput Permit2TypedDataOutput) TokenizedAssetsTransferResponseEip712 {
	typ := TokenizedAssetsTransferResponseEip712TypePermit2TypedDataOutput

	return TokenizedAssetsTransferResponseEip712{
		Permit2TypedDataOutput: &permit2TypedDataOutput,
		Type:                   typ,
	}
}

func CreateTokenizedAssetsTransferResponseEip712Unknown(raw json.RawMessage) TokenizedAssetsTransferResponseEip712 {
	return TokenizedAssetsTransferResponseEip712{
		UnknownRaw: raw,
		Type:       TokenizedAssetsTransferResponseEip712TypeUnknown,
	}
}

func (u TokenizedAssetsTransferResponseEip712) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u TokenizedAssetsTransferResponseEip712) IsUnknown() bool {
	return u.Type == TokenizedAssetsTransferResponseEip712TypeUnknown
}

func (u *TokenizedAssetsTransferResponseEip712) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var batchedSafeOperationsResponseOutput BatchedSafeOperationsResponseOutput = BatchedSafeOperationsResponseOutput{}
	if err := utils.UnmarshalJSON(data, &batchedSafeOperationsResponseOutput, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TokenizedAssetsTransferResponseEip712TypeBatchedSafeOperationsResponseOutput,
			Value: &batchedSafeOperationsResponseOutput,
		})
	}

	var permit2TypedDataOutput Permit2TypedDataOutput = Permit2TypedDataOutput{}
	if err := utils.UnmarshalJSON(data, &permit2TypedDataOutput, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  TokenizedAssetsTransferResponseEip712TypePermit2TypedDataOutput,
			Value: &permit2TypedDataOutput,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = TokenizedAssetsTransferResponseEip712TypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = TokenizedAssetsTransferResponseEip712TypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(TokenizedAssetsTransferResponseEip712Type)
	switch best.Type {
	case TokenizedAssetsTransferResponseEip712TypeBatchedSafeOperationsResponseOutput:
		u.BatchedSafeOperationsResponseOutput = best.Value.(*BatchedSafeOperationsResponseOutput)
		return nil
	case TokenizedAssetsTransferResponseEip712TypePermit2TypedDataOutput:
		u.Permit2TypedDataOutput = best.Value.(*Permit2TypedDataOutput)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = TokenizedAssetsTransferResponseEip712TypeUnknown
	return nil
}

func (u TokenizedAssetsTransferResponseEip712) MarshalJSON() ([]byte, error) {
	if u.BatchedSafeOperationsResponseOutput != nil {
		return utils.MarshalJSON(u.BatchedSafeOperationsResponseOutput, "", true)
	}

	if u.Permit2TypedDataOutput != nil {
		return utils.MarshalJSON(u.Permit2TypedDataOutput, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type TokenizedAssetsTransferResponseEip712: all fields are null")
}

type TokenizedAssetsTransferResponse struct {
	// Unsigned transaction for direct execution. Present when `gas_sponsorship=false`.
	Transaction optionalnullable.OptionalNullable[UnsignedTransaction] `json:"transaction,omitzero"`
	// EIP-712 typed data for gas-sponsored execution. Present when `gas_sponsorship=true`. A Permit2 `PermitTransferFrom` for DEPOSIT, or a Safe transaction for WITHDRAW. The owner signs it and submits to `/v2/gas_sponsorship/prepare`.
	Eip712 optionalnullable.OptionalNullable[TokenizedAssetsTransferResponseEip712] `json:"eip_712,omitzero"`
}

func (t TokenizedAssetsTransferResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TokenizedAssetsTransferResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TokenizedAssetsTransferResponse) GetTransaction() optionalnullable.OptionalNullable[UnsignedTransaction] {
	if t == nil {
		return nil
	}
	return t.Transaction
}

func (t *TokenizedAssetsTransferResponse) GetEip712() optionalnullable.OptionalNullable[TokenizedAssetsTransferResponseEip712] {
	if t == nil {
		return nil
	}
	return t.Eip712
}
