// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TokenizedEquitiesMarketsListResponse - List of tokenized equity markets.
type TokenizedEquitiesMarketsListResponse struct {
	// Tokenized equity markets surfaced on Ethereum.
	Markets []CompassAPIBackendV2ModelsTokenizedEquitiesMarketMarket `json:"markets"`
}

func (t *TokenizedEquitiesMarketsListResponse) GetMarkets() []CompassAPIBackendV2ModelsTokenizedEquitiesMarketMarket {
	if t == nil {
		return []CompassAPIBackendV2ModelsTokenizedEquitiesMarketMarket{}
	}
	return t.Markets
}
