// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
)

// TokenizedAssetsPositionsResponseChain - Chain on which the balances were read.
type TokenizedAssetsPositionsResponseChain string

const (
	TokenizedAssetsPositionsResponseChainEthereum TokenizedAssetsPositionsResponseChain = "ethereum"
)

func (e TokenizedAssetsPositionsResponseChain) ToPointer() *TokenizedAssetsPositionsResponseChain {
	return &e
}
func (e *TokenizedAssetsPositionsResponseChain) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ethereum":
		*e = TokenizedAssetsPositionsResponseChain(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TokenizedAssetsPositionsResponseChain: %v", v)
	}
}

// TokenizedAssetsPositionsResponse - Wallet's on-chain tokenized-asset holdings.
type TokenizedAssetsPositionsResponse struct {
	// Queried wallet.
	Wallet string `json:"wallet"`
	// Chain on which the balances were read.
	Chain *TokenizedAssetsPositionsResponseChain `json:"chain,omitzero"`
	// Non-zero positions only; tokens with a zero balance are omitted.
	Positions []CompassAPIBackendV2ModelsTokenizedAssetsReadResponsePositionsPosition `json:"positions,omitzero"`
	// Sum of `balance_usd` across positions where the price is known.
	TotalUsd string `json:"total_usd"`
}

func (t TokenizedAssetsPositionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TokenizedAssetsPositionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TokenizedAssetsPositionsResponse) GetWallet() string {
	if t == nil {
		return ""
	}
	return t.Wallet
}

func (t *TokenizedAssetsPositionsResponse) GetChain() *TokenizedAssetsPositionsResponseChain {
	if t == nil {
		return nil
	}
	return t.Chain
}

func (t *TokenizedAssetsPositionsResponse) GetPositions() []CompassAPIBackendV2ModelsTokenizedAssetsReadResponsePositionsPosition {
	if t == nil {
		return nil
	}
	return t.Positions
}

func (t *TokenizedAssetsPositionsResponse) GetTotalUsd() string {
	if t == nil {
		return ""
	}
	return t.TotalUsd
}
