// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TokenizedEquitiesCancelOrderRequest struct {
	// Wallet that owns the Tokenized Equities Account. The account address derived from this owner must match the order's on-chain maker; the API rejects otherwise (only the order's maker can cancel it).
	Owner string `json:"owner"`
}

func (t *TokenizedEquitiesCancelOrderRequest) GetOwner() string {
	if t == nil {
		return ""
	}
	return t.Owner
}
