// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TokenizedAssetsCancelOrderResponse struct {
	// Response containing EIP-712 typed data for Safe transaction signing.
	CancelSafeTxEip712 BatchedSafeOperationsResponseOutput `json:"cancel_safe_tx_eip712"`
}

func (t *TokenizedAssetsCancelOrderResponse) GetCancelSafeTxEip712() BatchedSafeOperationsResponseOutput {
	if t == nil {
		return BatchedSafeOperationsResponseOutput{}
	}
	return t.CancelSafeTxEip712
}
