// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TokenizedEquitiesOhlcRange string

const (
	TokenizedEquitiesOhlcRangeOneday     TokenizedEquitiesOhlcRange = "1day"
	TokenizedEquitiesOhlcRangeOnemonth   TokenizedEquitiesOhlcRange = "1month"
	TokenizedEquitiesOhlcRangeThreemonth TokenizedEquitiesOhlcRange = "3month"
	TokenizedEquitiesOhlcRangeSixmonth   TokenizedEquitiesOhlcRange = "6month"
	TokenizedEquitiesOhlcRangeOneyear    TokenizedEquitiesOhlcRange = "1year"
	TokenizedEquitiesOhlcRangeAll        TokenizedEquitiesOhlcRange = "all"
)

func (e TokenizedEquitiesOhlcRange) ToPointer() *TokenizedEquitiesOhlcRange {
	return &e
}
func (e *TokenizedEquitiesOhlcRange) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "1day":
		fallthrough
	case "1month":
		fallthrough
	case "3month":
		fallthrough
	case "6month":
		fallthrough
	case "1year":
		fallthrough
	case "all":
		*e = TokenizedEquitiesOhlcRange(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TokenizedEquitiesOhlcRange: %v", v)
	}
}
