// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TokenizedAssetsQuoteRequest - Preview a buy or sell quote for a tokenized equity.
//
// Read-only: this previews a quote without consuming a “quote_id“ or
// committing an order. Use it to surface expected output, fees, and a
// thin-liquidity warning before the user confirms; pass
// the same body (plus “slippage_bps“) to “POST /tokenized_assets/order“
// when they do.
type TokenizedAssetsQuoteRequest struct {
	// Token the sender is paying. Either an on-chain symbol (e.g. `TSLAon`), the literal `USDC`, or a 0x-prefixed token address.
	FromToken string `json:"from_token"`
	// Token the sender is receiving. Same accepted forms as `from_token`.
	ToToken string `json:"to_token"`
	// Human-readable amount of `from_token` to swap (decimal string). Decimals are applied server-side.
	Amount string `json:"amount"`
	// Wallet that owns the Tokenized Assets Account. Used to verify the account is deployed before quoting; the account address is derived deterministically from this owner.
	Owner string `json:"owner"`
}

func (t *TokenizedAssetsQuoteRequest) GetFromToken() string {
	if t == nil {
		return ""
	}
	return t.FromToken
}

func (t *TokenizedAssetsQuoteRequest) GetToToken() string {
	if t == nil {
		return ""
	}
	return t.ToToken
}

func (t *TokenizedAssetsQuoteRequest) GetAmount() string {
	if t == nil {
		return ""
	}
	return t.Amount
}

func (t *TokenizedAssetsQuoteRequest) GetOwner() string {
	if t == nil {
		return ""
	}
	return t.Owner
}
