// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TraditionalInvestingApproveBuilderFeeRequest - Request to approve builder fees before trading on the traditional investing DEX.
type TraditionalInvestingApproveBuilderFeeRequest struct {
	// User's EOA address
	Owner string `json:"owner"`
}

func (t *TraditionalInvestingApproveBuilderFeeRequest) GetOwner() string {
	if t == nil {
		return ""
	}
	return t.Owner
}
