// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TraditionalInvestingEnsureLeverageRequest - Request to check and set leverage to 1x cross on a traditional investing asset.
type TraditionalInvestingEnsureLeverageRequest struct {
	// User's EOA address
	Owner string `json:"owner"`
	// Asset ticker (e.g. 'AAPL', 'CL')
	Asset string `json:"asset"`
}

func (t *TraditionalInvestingEnsureLeverageRequest) GetOwner() string {
	if t == nil {
		return ""
	}
	return t.Owner
}

func (t *TraditionalInvestingEnsureLeverageRequest) GetAsset() string {
	if t == nil {
		return ""
	}
	return t.Asset
}
