// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/CompassLabs/cli/internal/sdk/optionalnullable"
)

// TraditionalInvestingWithdrawRequest - Request to withdraw USDC from HyperEVM traditional investing account to Arbitrum.
type TraditionalInvestingWithdrawRequest struct {
	// The user's EOA address (owner of the traditional investing account)
	Owner string `json:"owner"`
	// USDC amount to withdraw (human-readable, e.g. '500.0')
	Amount string `json:"amount"`
	// Arbitrum destination address (defaults to owner if not specified)
	Destination optionalnullable.OptionalNullable[string] `json:"destination,omitzero"`
}

func (t *TraditionalInvestingWithdrawRequest) GetOwner() string {
	if t == nil {
		return ""
	}
	return t.Owner
}

func (t *TraditionalInvestingWithdrawRequest) GetAmount() string {
	if t == nil {
		return ""
	}
	return t.Amount
}

func (t *TraditionalInvestingWithdrawRequest) GetDestination() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Destination
}
