// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TraditionalInvestingOpportunitiesResponse - List of available traditional investing perpetual futures markets.
type TraditionalInvestingOpportunitiesResponse struct {
	// Available traditional investing perp markets
	Opportunities []TraditionalInvestingOpportunity `json:"opportunities"`
}

func (t *TraditionalInvestingOpportunitiesResponse) GetOpportunities() []TraditionalInvestingOpportunity {
	if t == nil {
		return []TraditionalInvestingOpportunity{}
	}
	return t.Opportunities
}
