// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/CompassLabs/cli/internal/sdk/sdkinternal/utils"
	"github.com/CompassLabs/cli/internal/sdk/types"
)

type ValueUsdType string

const (
	ValueUsdTypeNumber ValueUsdType = "number"
	ValueUsdTypeStr    ValueUsdType = "str"
)

type ValueUsd struct {
	Number *float64 `queryParam:"inline" union:"member"`
	Str    *string  `queryParam:"inline" union:"member"`

	Type ValueUsdType
}

func CreateValueUsdNumber(number float64) ValueUsd {
	typ := ValueUsdTypeNumber

	return ValueUsd{
		Number: &number,
		Type:   typ,
	}
}

func CreateValueUsdStr(str string) ValueUsd {
	typ := ValueUsdTypeStr

	return ValueUsd{
		Str:  &str,
		Type: typ,
	}
}

func (u *ValueUsd) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = ValueUsd{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueUsdTypeNumber,
			Value: &number,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ValueUsdTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValueUsd", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValueUsd", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ValueUsdType)
	switch best.Type {
	case ValueUsdTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	case ValueUsdTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ValueUsd", string(data))
}

func (u ValueUsd) MarshalJSON() ([]byte, error) {
	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type ValueUsd: all fields are null")
}

// UsdDeposit - A dollar figure, for analytics only.
//
// Enough to answer "what would this look like", not enough to build a
// transaction — the API will not choose which of your tokens to spend.
type UsdDeposit struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_    *string  `const:"usd" json:"type,omitzero"`
	ValueUsd ValueUsd `json:"value_usd"`
}

func (u UsdDeposit) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UsdDeposit) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UsdDeposit) GetType() *string {
	return types.Pointer("usd")
}

func (u *UsdDeposit) GetValueUsd() ValueUsd {
	if u == nil {
		return ValueUsd{}
	}
	return u.ValueUsd
}
