// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package traditionalinvesting

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var traditionalInvestingEnsureLeverageCmdMeta = []flagutil.FlagMeta{
	{FlagName: "owner", FieldPath: "Owner", Kind: flagutil.FlagKindString, Required: true, Description: "User's EOA address [required]"},
	{FlagName: "asset", Shorthand: "a", FieldPath: "Asset", Kind: flagutil.FlagKindString, Required: true, Description: "Asset ticker (e.g. 'AAPL', 'CL') [required]"},
}

// initTraditionalInvestingEnsureLeverageCmd initializes the traditional-investing-ensure-leverage command.
func initTraditionalInvestingEnsureLeverageCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "traditional-investing-ensure-leverage",
		Short:   "Ensure 1x cross leverage",
		Long:    "Check leverage and prepare an updateLeverage action if not 1x cross.\n\nIf the asset is already at 1x cross leverage, returns leverage_ok=true\nwith null typed_data — no signing needed. Otherwise, returns EIP-712\ntyped data for the user to sign. After signing, submit the signature\nvia the /execute endpoint.",
		Example: "  compass traditional-investing traditional-investing-ensure-leverage --owner <value> --asset <value>",
		RunE:    runTraditionalInvestingEnsureLeverageCmd,
		Aliases: []string{"tiel"},
	}
	flagutil.RegisterFlags(cmd, traditionalInvestingEnsureLeverageCmdMeta)
	if err := flagutil.ValidateMeta[components.TraditionalInvestingEnsureLeverageRequest](traditionalInvestingEnsureLeverageCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for traditional-investing-ensure-leverage: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runTraditionalInvestingEnsureLeverageCmd executes the traditional-investing-ensure-leverage command.
func runTraditionalInvestingEnsureLeverageCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, traditionalInvestingEnsureLeverageCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, traditionalInvestingEnsureLeverageCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.TraditionalInvestingEnsureLeverageRequest](cmd, traditionalInvestingEnsureLeverageCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.TraditionalInvesting.TraditionalInvestingEnsureLeverage(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
