// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package traditionalinvesting

import (
	"fmt"
	"github.com/CompassLabs/cli/internal/client"
	"github.com/CompassLabs/cli/internal/flagutil"
	"github.com/CompassLabs/cli/internal/interactive"
	"github.com/CompassLabs/cli/internal/output"
	"github.com/CompassLabs/cli/internal/sdk"
	"github.com/CompassLabs/cli/internal/sdk/models/components"
	"github.com/CompassLabs/cli/internal/sdk/models/operations"
	"github.com/CompassLabs/cli/internal/usage"
	"github.com/spf13/cobra"
)

var traditionalInvestingDepositCmdMeta = []flagutil.FlagMeta{
	{FlagName: "owner", FieldPath: "Owner", Kind: flagutil.FlagKindString, Required: true, Description: "The user's EOA address on Arbitrum [required]"},
	{FlagName: "amount", Shorthand: "a", FieldPath: "Amount", Kind: flagutil.FlagKindString, Required: true, Description: "USDC amount to deposit (human-readable, e.g. '1000.0') [required]"},
}

// initTraditionalInvestingDepositCmd initializes the traditional-investing-deposit command.
func initTraditionalInvestingDepositCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "traditional-investing-deposit",
		Short:   "Deposit USDC to traditional investments account",
		Long:    "Prepare a USDC deposit from Arbitrum via EIP-2612 Permit.\n\nReturns EIP-712 typed data for the user to sign off-chain (no gas needed).\nAfter signing, send the permit signature to the deposit/execute endpoint,\nwhere a gas sponsor calls batchedDepositWithPermit on the HL Bridge2.",
		Example: "  compass traditional-investing traditional-investing-deposit --owner 0x01E62835dd7F52173546A325294762143eE4a882 --amount 100.0",
		RunE:    runTraditionalInvestingDepositCmd,
		Aliases: []string{"tid"},
	}
	flagutil.RegisterFlags(cmd, traditionalInvestingDepositCmdMeta)
	if err := flagutil.ValidateMeta[components.TraditionalInvestingDepositRequest](traditionalInvestingDepositCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for traditional-investing-deposit: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runTraditionalInvestingDepositCmd executes the traditional-investing-deposit command.
func runTraditionalInvestingDepositCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, traditionalInvestingDepositCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, traditionalInvestingDepositCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.TraditionalInvestingDepositRequest](cmd, traditionalInvestingDepositCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.TraditionalInvesting.TraditionalInvestingDeposit(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
